<template>
  <main class="performance-page">
    <header class="performance-hero">
      <div><span>基于事实的反馈</span><h1>绩效反馈与月度闭环</h1><p>分数只用于回看交付、质量和协同事实；不提供排名，也不替代管理沟通。</p></div>
      <div class="performance-hero__controls"><el-date-picker v-model="period" type="month" value-format="yyyy-MM" format="yyyy-MM" :clearable="false" @change="loadAll" /><el-button v-if="manager" v-hasPermi="['lab:perf:close']" plain @click="closePeriod">关闭周期</el-button><el-button v-if="manager" v-hasPermi="['lab:perf:reopen']" plain @click="reopenPeriod">重开周期</el-button></div>
    </header>

    <div class="principle"><i class="el-icon-info" /><strong>反馈原则</strong><span>不横向排名；所有结论必须回到截止快照、任务证据、质量门禁和协同审核事实。</span></div>
    <el-tabs v-model="tab" class="performance-tabs">
      <el-tab-pane label="我的反馈" name="mine">
        <section class="feedback-layout">
          <aside class="feedback-list"><header><span>当前修订</span><h2>个人月度反馈</h2></header><button v-for="item in myScores" :key="item.id" :class="{ active: selected && selected.id === item.id }" type="button" @click="selected=item"><div><strong>{{ item.period }}</strong><small>修订 {{ item.revisionNo }} · {{ confirmationLabel(item.confirmationStatus) }}</small></div><b :class="{ red: activeRedLine(item) }">{{ number(item.score) }}</b></button><el-empty v-if="!myScores.length" description="该周期暂无已关闭反馈" :image-size="65" /></aside>
          <article class="breakdown-panel"><score-breakdown :score="selected" :member-name="memberName(selected && selected.memberId)" /><div v-if="selected" class="feedback-actions"><el-button v-if="selected.confirmationStatus !== 'CONFIRMED'" v-hasPermi="['lab:perf:list']" type="primary" :disabled="activeRedLine(selected) && !manager" @click="confirm(selected)">确认收到反馈</el-button><small v-if="activeRedLine(selected) && !manager">活动红线由实验室负责人处理后才能由成员确认</small></div></article>
        </section>
      </el-tab-pane>

      <el-tab-pane v-if="manager" label="团队反馈" name="team">
        <section class="team-panel">
          <header><div><span>非排名式回顾</span><h2>团队事实反馈</h2><p>按成员编号稳定展示，不进行高低排序。</p></div><el-button v-hasPermi="['lab:perf:close']" icon="el-icon-view" :disabled="!activeMemberId" @click="preview">预览当前成员</el-button></header>
          <div class="team-grid"><button v-for="item in teamScores" :key="item.id" :class="{ active: teamSelected && teamSelected.id === item.id }" type="button" @click="selectTeam(item)"><span>{{ memberInitials(item.memberId) }}</span><div><strong>{{ memberName(item.memberId) }}</strong><small>修订 {{ item.revisionNo }} · {{ resultLabel(item) }}</small></div><b :class="{ red: activeRedLine(item) }">{{ number(item.score) }}</b></button><div v-if="!teamScores.length" class="team-empty">当前周期尚未关闭，选择成员可先预览事实。</div></div>
          <div class="manager-actions"><el-select v-model="activeMemberId" filterable placeholder="选择成员" @change="managerMemberChanged"><el-option v-for="member in activeMembers" :key="member.id" :label="memberLabel(member)" :value="member.id" /></el-select><el-button v-hasPermi="['lab:perf:history']" :disabled="!activeMemberId" @click="loadRevisions">修订历史</el-button><el-button v-if="teamSelected && activeRedLine(teamSelected)" v-hasPermi="['lab:perf:revoke']" type="danger" plain @click="openRevoke(teamSelected)">撤销红线</el-button><el-button v-hasPermi="['lab:perf:calibrate']" :disabled="!activeMemberId" @click="openCalibration">季度校准</el-button></div>
          <article class="breakdown-panel manager"><score-breakdown :score="teamSelected || previewScore" :member-name="memberName(activeMemberId)" /></article>
        </section>
      </el-tab-pane>

      <el-tab-pane label="协同事实" name="collaboration">
        <section class="collaboration-panel">
          <header><div><span>经审核的协同事实</span><h2>协同贡献与扣分事实</h2><p>正向事实必须有证据；创建者不能审核自己的记录。</p></div><el-button v-hasPermi="['lab:perf:list']" type="primary" icon="el-icon-plus" @click="openCollaboration">登记协同事实</el-button></header>
          <el-table v-loading="collaborationLoading" :data="collaboration" row-key="id"><el-table-column label="类别" width="140"><template slot-scope="scope"><span class="category">{{ categoryLabel(scope.row.category) }}</span></template></el-table-column><el-table-column label="目标成员" min-width="140"><template slot-scope="scope">{{ memberName(scope.row.toMemberId) }}</template></el-table-column><el-table-column label="提议分值" width="100"><template slot-scope="scope"><strong :class="{ negative: Number(scope.row.signedScore)<0 }">{{ signed(scope.row.signedScore) }}</strong></template></el-table-column><el-table-column label="证据" width="105"><template slot-scope="scope"><el-button v-if="safeUrl(scope.row.evidenceUrl)" type="text" @click="openUrl(scope.row.evidenceUrl)">查看证据</el-button><span v-else>—</span></template></el-table-column><el-table-column label="审核" min-width="150"><template slot-scope="scope"><el-tag :type="scope.row.reviewStatus === 'APPROVED' ? 'success' : 'warning'" size="mini" effect="plain">{{ reviewStatusLabel(scope.row.reviewStatus) }}</el-tag><small v-if="scope.row.reviewComment" class="review-comment">{{ scope.row.reviewComment }}</small></template></el-table-column><el-table-column label="操作" width="100"><template slot-scope="scope"><el-button v-if="scope.row.reviewStatus === 'PENDING' && currentMemberId != null && Number(scope.row.fromMemberId) !== Number(currentMemberId)" v-hasPermi="['lab:perf:close']" type="text" @click="openReview(scope.row)">审核</el-button></template></el-table-column><template slot="empty"><el-empty description="该周期暂无协同事实" /></template></el-table>
        </section>
      </el-tab-pane>
    </el-tabs>

    <el-dialog title="登记协同事实" :visible.sync="collaborationVisible" width="590px" append-to-body><el-form ref="collaborationForm" :model="collaborationForm" :rules="collaborationRules" label-position="top"><el-row :gutter="14"><el-col :span="12"><el-form-item label="目标成员" prop="toMemberId"><el-select v-model="collaborationForm.toMemberId" filterable><el-option v-for="member in activeMembers" :key="member.id" :label="memberLabel(member)" :value="member.id" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="类别" prop="category"><el-select v-model="collaborationForm.category" @change="categoryChanged"><el-option v-for="item in availableCategories" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item></el-col></el-row><el-row :gutter="14"><el-col :span="12"><el-form-item label="任务 ID"><el-input-number v-model="collaborationForm.taskId" :min="1" controls-position="right" /></el-form-item></el-col><el-col :span="12"><el-form-item label="提议分值" prop="signedScore"><el-input-number v-model="collaborationForm.signedScore" :min="negativeCategory ? -100 : 0" :max="negativeCategory ? 0 : 100" :precision="2" controls-position="right" /></el-form-item></el-col></el-row><el-form-item label="证据链接" :required="!negativeCategory"><el-input v-model.trim="collaborationForm.evidenceUrl" placeholder="https://…" /></el-form-item><el-form-item label="事实说明"><el-input v-model.trim="collaborationForm.remark" type="textarea" :rows="3" /></el-form-item></el-form><span slot="footer"><el-button @click="collaborationVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveCollaboration">提交审核</el-button></span></el-dialog>

    <el-dialog title="审核协同事实" :visible.sync="reviewVisible" width="520px" append-to-body><el-form :model="reviewForm" label-position="top"><el-form-item label="核准分值"><el-input-number v-model="reviewForm.approvedScore" :precision="2" :min="reviewNegative ? -100 : 0" :max="reviewNegative ? 0 : 100" /></el-form-item><el-form-item label="审核意见"><el-input v-model.trim="reviewForm.comment" type="textarea" :rows="3" /></el-form-item></el-form><span slot="footer"><el-button @click="reviewVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitReview">确认审核</el-button></span></el-dialog>

    <el-dialog title="红线整改撤销" :visible.sync="revokeVisible" width="540px" append-to-body><div class="redline-warning">只撤销当前红线状态，不删除原触发事实；整改证据与原因将进入审计快照。</div><el-form :model="revokeForm" label-position="top"><el-form-item label="整改证据链接"><el-input v-model.trim="revokeForm.evidenceUrl" placeholder="https://…" /></el-form-item><el-form-item label="撤销原因"><el-input v-model.trim="revokeForm.reason" type="textarea" :rows="3" /></el-form-item></el-form><span slot="footer"><el-button @click="revokeVisible=false">取消</el-button><el-button type="danger" :loading="saving" @click="submitRevoke">确认撤销红线</el-button></span></el-dialog>

    <el-dialog title="季度校准" :visible.sync="calibrationVisible" width="520px" append-to-body><el-form :model="calibrationForm" label-position="top"><el-form-item label="季度"><el-select v-model="calibrationForm.quarter"><el-option v-for="quarter in quarterOptions" :key="quarter" :label="quarter" :value="quarter" /></el-select></el-form-item><el-form-item label="校准分数"><el-input-number v-model="calibrationForm.score" :min="0" :max="100" :precision="2" /></el-form-item><el-form-item label="校准说明"><el-input v-model.trim="calibrationForm.comment" type="textarea" :rows="3" /></el-form-item></el-form><span slot="footer"><el-button @click="calibrationVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitCalibration">保存校准</el-button></span></el-dialog>

    <el-drawer title="绩效修订历史" :visible.sync="revisionsVisible" size="62%" append-to-body><div class="revision-list"><button v-for="item in revisions" :key="item.id" type="button" @click="teamSelected=item"><span>R{{ item.revisionNo }}</span><div><strong>{{ item.period }} · {{ number(item.score) }}</strong><small>{{ item.currentFlag === '1' ? '当前修订' : '历史修订' }} · 截止 {{ item.cutoffTime || '—' }}</small></div></button><score-breakdown :score="teamSelected" :member-name="memberName(activeMemberId)" /></div></el-drawer>
  </main>
</template>

<script>
import { listMembers } from '@/api/lab/member'
import { addCollaboration, calibrateQuarter, closePerformancePeriod, confirmPerformance, listCollaboration, listMyPerformance, listPerformance, listRevisions, previewPerformance, reopenPerformancePeriod, reviewCollaboration, revokeRedLine } from '@/api/lab/performance'
import ScoreBreakdown from './components/ScoreBreakdown'

export default {
  name: 'LabPerformance', components: { ScoreBreakdown },
  data() { return { tab: 'mine', period: this.$route.query.period || this.currentPeriod(), myScores: [], teamScores: [], collaboration: [], members: [], selected: null, teamSelected: null, previewScore: null, activeMemberId: this.numberOrNull(this.$route.query.memberId), myToken: 0, teamToken: 0, collaborationToken: 0, previewToken: 0, revisionToken: 0, collaborationLoading: false, saving: false, collaborationVisible: false, reviewVisible: false, revokeVisible: false, calibrationVisible: false, revisionsVisible: false, collaborationForm: {}, reviewForm: {}, reviewing: null, revoking: null, revokeForm: {}, calibrationForm: {}, revisions: [], categories: [{ label: '跨部门支持', value: 'CROSS_DEPT' }, { label: '知识分享', value: 'KNOWLEDGE' }, { label: '备份培养', value: 'BACKUP' }, { label: '逾期扣分', value: 'OVERDUE' }, { label: '人工扣分', value: 'DEDUCTION' }], collaborationRules: { toMemberId: [{ required: true, message: '请选择目标成员', trigger: 'change' }], category: [{ required: true, message: '请选择类别', trigger: 'change' }], signedScore: [{ required: true, message: '请输入分值', trigger: 'change' }] }} },
  computed: {
    manager() { const roles = (this.$store.getters.roles || []).map(item => String(item).toLowerCase()); return roles.includes('admin') || roles.includes('lab_manager') || roles.includes('manager') }, activeMembers() { return this.members.filter(item => item.memberStatus === 'ACTIVE') }, currentMemberId() { const member = this.members.find(item => Number(item.userId) === Number(this.$store.state.user.id)); return member ? member.id : null }, availableCategories() { return this.categories.filter(item => ['CROSS_DEPT', 'KNOWLEDGE', 'BACKUP'].includes(item.value) || (this.manager && item.value === 'DEDUCTION')) }, negativeCategory() { return ['OVERDUE', 'DEDUCTION'].includes(this.collaborationForm.category) }, reviewNegative() { return this.reviewing && ['OVERDUE', 'DEDUCTION'].includes(this.reviewing.category) }, quarterOptions() { const year = this.period.slice(0, 4); return [1, 2, 3, 4].map(value => `${year}-Q${value}`) }
  },
  created() { this.loadMembers(); this.loadAll() },
  methods: {
    loadMembers() { listMembers({ pageNum: 1, pageSize: 500 }).then(res => { this.members = res.rows || [] }) },
    loadAll() { this.selected = null; this.teamSelected = null; this.previewScore = null; this.myScores = []; this.teamScores = []; this.collaboration = []; const requests = [this.loadMine(), this.loadCollaboration()]; if (this.manager) requests.push(this.loadTeam()); return Promise.all(requests) },
    loadMine() { const period = this.period; const token = ++this.myToken; return listMyPerformance(period).then(res => { if (token !== this.myToken || period !== this.period) return; this.myScores = res.data || []; this.selected = this.myScores.find(item => item.currentFlag === '1') || this.myScores[0] || null }) },
    loadTeam() { const period = this.period; const token = ++this.teamToken; return listPerformance(period).then(res => { if (token !== this.teamToken || period !== this.period) return; this.teamScores = res.data || []; this.teamSelected = this.activeMemberId ? this.teamScores.find(item => Number(item.memberId) === Number(this.activeMemberId)) || null : null }) },
    loadCollaboration() { const period = this.period; const token = ++this.collaborationToken; this.collaborationLoading = true; return listCollaboration(period).then(res => { if (token !== this.collaborationToken || period !== this.period) return; this.collaboration = res.data || [] }).finally(() => { if (token === this.collaborationToken) this.collaborationLoading = false }) }, selectTeam(item) { this.previewToken += 1; this.revisionToken += 1; this.revisionsVisible = false; this.teamSelected = item; this.activeMemberId = item.memberId; this.previewScore = null }, managerMemberChanged() { this.previewToken += 1; this.revisionToken += 1; this.previewScore = null; this.revisionsVisible = false; this.teamSelected = this.teamScores.find(item => Number(item.memberId) === Number(this.activeMemberId)) || null },
    preview() { if (!this.activeMemberId) return; const memberId = this.activeMemberId; const period = this.period; const token = ++this.previewToken; previewPerformance(memberId, period).then(res => { if (token !== this.previewToken || period !== this.period || Number(memberId) !== Number(this.activeMemberId)) return; this.previewScore = { ...(res.data || {}), memberId, period, revisionNo: '预览', detailJson: (res.data || {}).detailJson }; this.teamSelected = null }) },
    loadRevisions() { const memberId = this.activeMemberId; const period = this.period; const token = ++this.revisionToken; listRevisions(memberId, period).then(res => { if (token !== this.revisionToken || period !== this.period || Number(memberId) !== Number(this.activeMemberId)) return; this.revisions = res.data || []; this.revisionsVisible = true }) },
    closePeriod() { this.$prompt('请输入关期原因；未确认的重点月任务会按未完成处理。', `关闭 ${this.period}`, { confirmButtonText: '确认关闭', inputValidator: value => Boolean(String(value || '').trim()) || '关期原因必填' }).then(({ value }) => closePerformancePeriod(this.period, value.trim())).then(() => { this.$message.success('周期已关闭并生成不可变修订'); this.loadAll() }).catch(() => {}) },
    reopenPeriod() { this.$prompt('重开会历史化当前分数并解锁任务，请输入原因。', `重开 ${this.period}`, { confirmButtonText: '确认重开', inputValidator: value => Boolean(String(value || '').trim()) || '重开原因必填' }).then(({ value }) => reopenPerformancePeriod(this.period, value.trim())).then(() => { this.$message.success('周期已重开'); this.loadAll() }).catch(() => {}) },
    confirm(item) { confirmPerformance(item.id, item.version).then(() => { this.$message.success('已确认收到反馈'); this.loadMine() }) },
    openCollaboration() { this.collaborationForm = { period: this.period, toMemberId: null, taskId: null, category: 'CROSS_DEPT', signedScore: 1, evidenceUrl: '', remark: '' }; this.collaborationVisible = true }, categoryChanged() { this.collaborationForm.signedScore = this.negativeCategory ? -1 : 1 },
    saveCollaboration() { this.$refs.collaborationForm.validate(valid => { if (!valid) return; if (!this.negativeCategory && !this.safeUrl(this.collaborationForm.evidenceUrl)) return this.$message.warning('正向协同必须填写有效的 http(s) 证据链接'); this.saving = true; addCollaboration(this.collaborationForm).then(() => { this.$message.success('协同事实已提交审核'); this.collaborationVisible = false; this.loadCollaboration() }).finally(() => { this.saving = false }) }) },
    openReview(item) { this.reviewing = item; this.reviewForm = { approvedScore: Number(item.signedScore), comment: '' }; this.reviewVisible = true }, submitReview() { if (!String(this.reviewForm.comment || '').trim()) return this.$message.warning('审核意见必填'); this.saving = true; reviewCollaboration(this.reviewing.id, this.reviewForm).then(() => { this.$message.success('协同事实已审核'); this.reviewVisible = false; this.loadCollaboration() }).finally(() => { this.saving = false }) },
    openRevoke(item) { this.revoking = item; this.revokeForm = { evidenceUrl: '', reason: '' }; this.revokeVisible = true }, submitRevoke() { if (!this.safeUrl(this.revokeForm.evidenceUrl) || !this.revokeForm.reason) return this.$message.warning('请填写有效整改证据链接和撤销原因'); this.saving = true; revokeRedLine(this.revoking.id, this.revokeForm).then(() => { this.$message.success('红线已撤销，原触发事实保留'); this.revokeVisible = false; this.loadAll() }).finally(() => { this.saving = false }) },
    openCalibration() { const month = Number(this.period.slice(5, 7)); this.calibrationForm = { quarter: `${this.period.slice(0, 4)}-Q${Math.floor((month - 1) / 3) + 1}`, score: 0, comment: '' }; this.calibrationVisible = true }, submitCalibration() { if (!this.calibrationForm.comment) return this.$message.warning('校准说明必填'); this.saving = true; calibrateQuarter(this.calibrationForm.quarter, this.activeMemberId, { score: this.calibrationForm.score, comment: this.calibrationForm.comment }).then(() => { this.$message.success('季度校准已保存'); this.calibrationVisible = false }).finally(() => { this.saving = false }) },
    activeRedLine(item) { return item && item.redLineFlag === '1' && item.revokedFlag !== '1' }, memberName(id) { const item = this.members.find(value => Number(value.id) === Number(id)); return item ? item.nickName || item.userName || item.memberNo : id ? `成员 #${id}` : '成员' }, memberInitials(id) { return this.memberName(id).slice(0, 2) }, memberLabel(item) { return `${item.nickName || item.userName || item.memberNo} · ${item.bizLine || '未分线'}` }, resultLabel(item) { return this.activeRedLine(item) ? '活动红线' : item.confirmationStatus === 'CONFIRMED' ? '已确认' : '待反馈确认' }, confirmationLabel(value) { return value === 'CONFIRMED' ? '已确认' : '待确认' }, reviewStatusLabel(value) { return ({ PENDING: '待审核', APPROVED: '已通过', REJECTED: '已退回' })[value] || '未定义状态' }, categoryLabel(value) { const item = this.categories.find(category => category.value === value); return item ? item.label : '未定义类别' }, signed(value) { const number = Number(value || 0); return `${number > 0 ? '+' : ''}${number.toFixed(2)}` }, number(value) { const parsed = Number(value || 0); return Number.isFinite(parsed) ? Number(parsed.toFixed(2)) : 0 }, safeUrl(url) { return /^https?:\/\//i.test(String(url || '')) }, openUrl(url) { if (this.safeUrl(url)) window.open(url, '_blank', 'noopener,noreferrer') }, currentPeriod() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}` }, numberOrNull(value) { const parsed = Number(value); return Number.isFinite(parsed) && parsed > 0 ? parsed : null }
  }
}
</script>

<style scoped lang="scss">
.performance-page { min-height:100%; padding:28px; color:#193641; background:#f2f5f4; }.performance-hero { display:flex; align-items:flex-end; justify-content:space-between; padding:28px 30px; color:#fff; border-radius:16px; background:linear-gradient(128deg,#102f3b,#17675f); }.performance-hero span { color:#a9dcd5; font-size:11px; letter-spacing:.17em; text-transform:uppercase; }.performance-hero h1 { margin:7px 0; font:600 30px Georgia,'Noto Serif SC',serif; }.performance-hero p { margin:0; color:#d6e6e3; }.performance-hero__controls { display:flex; gap:9px; }.performance-hero__controls ::v-deep .el-input__inner { color:#173941; background:#fff; }
.principle { display:flex; gap:9px; align-items:center; margin:14px 0 3px; padding:11px 15px; color:#45636a; border:1px solid #d8e4e1; border-radius:8px; background:#f9fbfa; }.principle strong { color:#225b56; }.performance-tabs ::v-deep .el-tabs__item { height:50px; line-height:50px; }.performance-tabs ::v-deep .el-tabs__active-bar { background:#0a746c; }.performance-tabs ::v-deep .el-tabs__item.is-active { color:#0a665f; }
.feedback-layout { display:grid; grid-template-columns:280px 1fr; gap:14px; }.feedback-list,.breakdown-panel,.team-panel,.collaboration-panel { padding:20px; border:1px solid #dce5e2; border-radius:12px; background:#fff; }.feedback-list header span,.team-panel>header span,.collaboration-panel>header span { color:#34716b; font-size:10px; letter-spacing:.15em; text-transform:uppercase; }.feedback-list h2,.team-panel h2,.collaboration-panel h2 { margin:5px 0; font:600 21px Georgia,'Noto Serif SC',serif; }.feedback-list>button { display:flex; align-items:center; justify-content:space-between; width:100%; margin-top:10px; padding:12px; text-align:left; border:1px solid #e0e7e5; border-radius:8px; background:#fff; cursor:pointer; }.feedback-list>button.active { border-color:#277970; background:#edf6f3; }.feedback-list button strong,.feedback-list button small { display:block; }.feedback-list button small { margin-top:3px; color:#79898f; }.feedback-list button b { font:600 20px Georgia,serif; color:#1d6d66; }.feedback-list button b.red,.team-grid b.red { color:#a44238; }.feedback-actions { display:flex; align-items:center; gap:12px; margin-top:16px; padding-top:14px; border-top:1px solid #e3e9e7; }.feedback-actions small { color:#976159; }
.team-panel>header,.collaboration-panel>header { display:flex; align-items:center; justify-content:space-between; }.team-panel header p,.collaboration-panel header p { margin:0; color:#75858b; }.team-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:9px; margin:17px 0; }.team-grid button { display:flex; align-items:center; gap:10px; padding:12px; text-align:left; border:1px solid #dfe7e4; border-radius:9px; background:#fbfcfc; cursor:pointer; }.team-grid button.active { border-color:#26756e; background:#eaf4f1; }.team-grid button>span { display:grid; flex:none; place-items:center; width:34px; height:34px; color:#1e645e; border-radius:9px; background:#dceeea; font-weight:700; }.team-grid button div { min-width:0; flex:1; }.team-grid strong,.team-grid small { display:block; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.team-grid small { margin-top:3px; color:#7a898f; }.team-grid b { color:#1c6b64; font:600 19px Georgia,serif; }.team-empty { grid-column:1/-1; padding:30px; color:#829096; text-align:center; }.manager-actions { display:flex; gap:9px; margin-bottom:14px; }.manager-actions .el-select { width:230px; }.breakdown-panel.manager { background:#fbfcfc; }
.collaboration-panel { min-height:420px; }.category { padding:4px 8px; color:#286860; border-radius:9px; background:#e9f3f0; }.negative { color:#a23e34; }.review-comment { display:block; margin-top:5px; color:#74858b; }.redline-warning { margin-bottom:13px; padding:11px; color:#8f3d35; border-radius:7px; background:#f9ece9; }.revision-list { padding:10px 24px 30px; }.revision-list>button { display:flex; width:100%; gap:12px; align-items:center; padding:11px; color:inherit; text-align:left; border:0; border-bottom:1px solid #e2e8e6; background:transparent; cursor:pointer; }.revision-list>button:hover,.revision-list>button:focus { background:#edf5f3; outline:2px solid transparent; }.revision-list>button>span { color:#286d66; font-weight:700; }.revision-list button strong,.revision-list button small { display:block; }.revision-list button small { color:#7d8b90; }
@media(max-width:1000px){.performance-page{padding:16px}.feedback-layout{grid-template-columns:1fr}.team-grid{grid-template-columns:1fr 1fr}.performance-hero{align-items:flex-start;gap:20px}.performance-hero__controls{flex-wrap:wrap}}
</style>
