package com.ailab.system.report.model;

import com.ailab.system.report.config.ReportSectionConfig;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.temporal.WeekFields;
import java.util.Locale;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/** Typed mapper inputs; no renderer/configuration value is ever SQL text. */
public final class ReportQueryCriteria {
    public static final int MAX_SOURCE_ROWS = 5000;
    public static final String SOURCE_FETCH_LIMIT_ATTRIBUTE = "reportSourceFetchLimit";
    private final String period; private final String nextPeriod; private final String monthStart; private final String monthEnd; private final java.sql.Date dateStart; private final java.sql.Date dateEnd; private final ReportPeriod reportPeriod; private final ReportAccessScope scope; private final List<Filter> filters; private final String sort; private final String groupBy; private final Integer performanceRevision; private final String targetBizLine; private final List<ReportPerformancePin> performancePins; private final int sourceFetchLimit; private final Long closeRevision; private final Long formalRevision; private final java.sql.Timestamp executionCutoff;
    public ReportQueryCriteria(String period, ReportAccessScope scope) {
        this.reportPeriod = ReportPeriod.parse(period); this.period = reportPeriod.getValue(); this.nextPeriod = reportPeriod.getKind()==ReportPeriod.Kind.MONTH ? reportPeriod.nextMonth() : null; LocalDate[] range = range(reportPeriod); this.monthStart = YearMonth.from(range[0]).toString(); this.monthEnd = YearMonth.from(range[1]).toString(); this.dateStart = java.sql.Date.valueOf(range[0]); this.dateEnd = java.sql.Date.valueOf(range[1]); this.scope = scope; this.filters = Collections.emptyList(); this.sort = null; this.groupBy = null; this.performanceRevision = null; this.targetBizLine=scope!=null&&scope.getKind()==ReportAccessScope.Kind.LEAD?scope.getBizLine():"ALL";this.performancePins=null;this.sourceFetchLimit=MAX_SOURCE_ROWS+1;this.closeRevision=null;this.formalRevision=null;this.executionCutoff=null;
    }
    private ReportQueryCriteria(String period, String targetBizLine, ReportAccessScope scope, List<Filter> filters, String sort, String groupBy, Integer performanceRevision, List<ReportPerformancePin> performancePins, int sourceFetchLimit, Long closeRevision, Long formalRevision, java.sql.Timestamp executionCutoff) { this.reportPeriod=ReportPeriod.parse(period); this.period = reportPeriod.getValue(); this.nextPeriod = reportPeriod.getKind()==ReportPeriod.Kind.MONTH ? reportPeriod.nextMonth() : null; LocalDate[] range = range(reportPeriod); this.monthStart = YearMonth.from(range[0]).toString(); this.monthEnd = YearMonth.from(range[1]).toString(); this.dateStart = java.sql.Date.valueOf(range[0]); this.dateEnd = java.sql.Date.valueOf(range[1]); this.scope = scope; this.filters = Collections.unmodifiableList(new ArrayList<Filter>(filters)); this.sort = sort; this.groupBy = groupBy; this.performanceRevision = performanceRevision;this.targetBizLine=targetBizLine;this.performancePins=performancePins==null?null:Collections.unmodifiableList(new ArrayList<ReportPerformancePin>(performancePins));this.sourceFetchLimit=sourceFetchLimit;this.closeRevision=closeRevision;this.formalRevision=formalRevision;this.executionCutoff=executionCutoff; }
    @SuppressWarnings("unchecked") public static ReportQueryCriteria from(ReportContext context, ReportSectionConfig section) {
        List<Filter> filters = new ArrayList<Filter>(); Object raw = section.getQueryConfig().get("filters"); ReportPeriod parsed=ReportPeriod.parse(context.getPeriod()); String next = parsed.getKind()==ReportPeriod.Kind.MONTH ? parsed.nextMonth() : null; if (raw instanceof Iterable) for (Object item : (Iterable<?>) raw) { Map<String,Object> value = (Map<String,Object>) item; filters.add(new Filter(String.valueOf(value.get("field")), String.valueOf(value.get("operator")), placeholder(value.get("value"), context.getPeriod(), next))); }
        Object sort = section.getQueryConfig().get("sort"), group = section.getQueryConfig().get("groupBy"), renderGroup = section.getRenderConfig().get("groupBy");
        if (group != null && renderGroup != null && !group.equals(renderGroup)) throw new IllegalArgumentException("Conflicting report groupBy");
        if (group == null) group = renderGroup;
        Object pinned = context.getAttributes().get("performanceRevision"); Integer performanceRevision = pinned instanceof Number ? ((Number) pinned).intValue() : null;
        return new ReportQueryCriteria(context.getPeriod(), context.getBizLine(), context.getAccessScope(), filters, sort instanceof String ? (String) sort : null, group instanceof String ? (String) group : null, performanceRevision, pins(context.getAttributes().get("performancePins")),sourceFetchLimit(context.getAttributes().get(SOURCE_FETCH_LIMIT_ATTRIBUTE)),context.getSourceCloseRevision(),context.getSourceFormalRevision(),context.getExecutionCutoff()==null?null:java.sql.Timestamp.from(context.getExecutionCutoff()));
    }
    public String getPeriod() { return period; } public String getNextPeriod() { return nextPeriod; } public String getPerformancePeriod(){return reportPeriod.getKind()==ReportPeriod.Kind.QUARTER ? period.substring(0,4)+"-Q"+period.charAt(5) : period;} public String getMonthStart(){return monthStart;} public String getMonthEnd(){return monthEnd;} public java.sql.Date getDateStart(){return new java.sql.Date(dateStart.getTime());} public java.sql.Date getDateEnd(){return new java.sql.Date(dateEnd.getTime());} public int getSourceFetchLimit(){return sourceFetchLimit;} public ReportPeriod getReportPeriod(){return reportPeriod;} public ReportAccessScope getScope() { return scope; } public List<Filter> getFilters() { return filters; } public String getSort() { return sort; } public String getGroupBy() { return groupBy; } public Integer getPerformanceRevision() { return performanceRevision; } public String getTargetBizLine(){return targetBizLine;} public List<ReportPerformancePin> getPerformancePins(){return performancePins;} public Long getCloseRevision(){return closeRevision;} public Long getFormalRevision(){return formalRevision;} public java.sql.Timestamp getExecutionCutoff(){return executionCutoff==null?null:new java.sql.Timestamp(executionCutoff.getTime());}
    private static int sourceFetchLimit(Object value){if(value==null)return MAX_SOURCE_ROWS+1;if(!(value instanceof Number))throw new IllegalArgumentException("Invalid report source fetch limit");int result=((Number)value).intValue();if(result<1||result>MAX_SOURCE_ROWS+1)throw new IllegalArgumentException("Invalid report source fetch limit");return result;}
    @SuppressWarnings("unchecked") private static List<ReportPerformancePin> pins(Object raw){if(raw==null)return null;if(!(raw instanceof Iterable))throw new IllegalArgumentException("Invalid performance pins");List<ReportPerformancePin> result=new ArrayList<ReportPerformancePin>();java.util.Set<Long> members=new java.util.HashSet<Long>();for(Object item:(Iterable<?>)raw){if(!(item instanceof Map))throw new IllegalArgumentException("Invalid performance pin");Map<String,Object> value=(Map<String,Object>)item;Object member=value.get("memberId"),revision=value.get("revisionNo");if(!(member instanceof Number)||!(revision instanceof Number))throw new IllegalArgumentException("Invalid performance pin");ReportPerformancePin pin=new ReportPerformancePin(((Number)member).longValue(),((Number)revision).intValue());if(!members.add(pin.getMemberId())||result.size()>=5000)throw new IllegalArgumentException("Invalid performance pins");result.add(pin);}return result;}
    public static final class Filter { private final String field, operator; private final Object value; Filter(String field, String operator, Object value) { this.field=field; this.operator=operator; this.value=ImmutableReportValue.value(value); } public String getField(){return field;} public String getOperator(){return operator;} public Object getValue(){return value;} }
    @SuppressWarnings("unchecked") private static Object placeholder(Object value, String period, String nextPeriod) { if (value instanceof String) { if ("${period}".equals(value)) return period; if ("${nextPeriod}".equals(value)) return nextPeriod; if (((String) value).contains("${")) throw new IllegalArgumentException("Unsupported report placeholder"); return value; } if (value instanceof List) { List<Object> result = new ArrayList<Object>(); for (Object item : (List<Object>) value) result.add(placeholder(item, period, nextPeriod)); return result; } return value; }
    private static LocalDate[] range(ReportPeriod period) { String value=period.getValue(); int year=Integer.parseInt(value.substring(0,4)); if(period.getKind()==ReportPeriod.Kind.MONTH){LocalDate start=LocalDate.of(year,Integer.parseInt(value.substring(5,7)),1);return new LocalDate[]{start,start.withDayOfMonth(start.lengthOfMonth())};} if(period.getKind()==ReportPeriod.Kind.QUARTER){int month=(Character.digit(value.charAt(5),10)-1)*3+1;LocalDate start=LocalDate.of(year,month,1);return new LocalDate[]{start,start.plusMonths(2).withDayOfMonth(start.plusMonths(2).lengthOfMonth())};} if(period.getKind()==ReportPeriod.Kind.YEAR)return new LocalDate[]{LocalDate.of(year,1,1),LocalDate.of(year,12,31)};int week=Integer.parseInt(value.substring(6,8));LocalDate start=LocalDate.of(year,1,4).with(WeekFields.ISO.weekOfWeekBasedYear(),week).with(WeekFields.ISO.dayOfWeek(),1);return new LocalDate[]{start,start.plusDays(6)}; }
}
