<template>
  <main class="asset-page">
    <header class="asset-hero"><div><span>Reusable capability ledger</span><h1>资产与主备覆盖</h1><p>资产价值由复用、交付阶段与可持续主备覆盖共同构成。</p></div><el-button v-hasPermi="['lab:asset:add']" type="primary" icon="el-icon-plus" @click="openCreate">登记资产</el-button></header>
    <section class="asset-insight">
      <article><span>资产总数</span><strong>{{ total }}</strong><small>当前授权列表</small></article><article class="risk"><span>单点风险</span><strong>{{ riskCount }}</strong><small>关键或在用资产缺少活跃备份</small></article><article><span>本页部署 / 验收</span><strong>{{ inUseCount }}</strong><small>当前页进入稳定使用阶段</small></article><article><span>本页累计复用</span><strong>{{ reuseTotal }}</strong><small>当前页可量化复用次数</small></article>
    </section>
    <section class="asset-ledger">
      <div class="filters"><el-input v-model.trim="query.assetName" clearable prefix-icon="el-icon-search" placeholder="资产名称" @keyup.enter.native="search" /><el-select v-model="query.assetType" clearable placeholder="资产类型" @change="search"><el-option label="硬件" value="hardware" /><el-option label="算法" value="algorithm" /><el-option label="平台" value="platform" /></el-select><el-select v-model="query.assetStage" clearable placeholder="阶段" @change="search"><el-option v-for="item in stages" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-checkbox v-model="query.singlePointRisk" @change="search">仅单点风险</el-checkbox><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></div>
      <div v-if="query.singlePointRisk" class="risk-note"><i class="el-icon-warning-outline" /> 风险口径：关键资产，或 ACTIVE 且已部署/验收的资产，没有活跃备份负责人。</div>
      <el-table v-loading="loading" :data="rows" row-key="id">
        <el-table-column label="资产" min-width="240"><template slot-scope="scope"><div class="asset-name"><span :class="{ 'is-risk': scope.row.singlePointRisk }">{{ typeMark(scope.row.assetType) }}</span><div><strong>{{ scope.row.assetName }}</strong><small>{{ scope.row.assetNo }} · {{ scope.row.assetVersion || '无版本' }}</small></div></div></template></el-table-column>
        <el-table-column label="阶段" width="110"><template slot-scope="scope"><span class="stage-pill">{{ stageLabel(scope.row.assetStage) }}</span></template></el-table-column><el-table-column label="主负责人" min-width="135"><template slot-scope="scope"><strong>{{ scope.row.primaryOwnerName || `#${scope.row.primaryOwnerId}` }}</strong><small class="sub">{{ scope.row.primaryOwnerBizLine || '—' }}</small></template></el-table-column><el-table-column label="备份人" min-width="125"><template slot-scope="scope"><span :class="{ muted: !scope.row.backupOwnerName }">{{ scope.row.backupOwnerName || '未配置' }}</span><small v-if="scope.row.backupOwnerStatus" class="sub">{{ scope.row.backupOwnerStatus }}</small></template></el-table-column>
        <el-table-column label="复用" width="80" align="center"><template slot-scope="scope">{{ Number(scope.row.reuseCount || 0) }}</template></el-table-column><el-table-column label="风险" width="115"><template slot-scope="scope"><span v-if="scope.row.singlePointRisk" class="risk-badge"><i class="el-icon-warning" /> 单点风险</span><span v-else class="covered"><i class="el-icon-circle-check" /> 已覆盖</span></template></el-table-column>
        <el-table-column label="制品" width="135"><template slot-scope="scope"><el-button v-if="safeUrl(scope.row.repositoryUrl)" type="text" @click="openUrl(scope.row.repositoryUrl)">仓库</el-button><el-button v-if="safeUrl(scope.row.documentUrl)" type="text" @click="openUrl(scope.row.documentUrl)">文档</el-button><span v-if="!safeUrl(scope.row.repositoryUrl) && !safeUrl(scope.row.documentUrl)">—</span></template></el-table-column>
        <el-table-column label="操作" width="145" fixed="right"><template slot-scope="scope"><template v-if="canWriteOwner(scope.row.primaryOwnerId)"><el-button v-hasPermi="['lab:asset:edit']" type="text" @click="openEdit(scope.row)">编辑</el-button><el-button v-hasPermi="['lab:asset:remove']" type="text" class="danger" :disabled="scope.row.status !== 'ACTIVE'" @click="deactivate(scope.row)">停用</el-button></template><span v-else class="muted">只读</span></template></el-table-column>
        <template slot="empty"><el-empty description="暂无匹配资产" /></template>
      </el-table><pagination v-show="total>0" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @pagination="load" />
    </section>

    <el-drawer :title="form.id ? '编辑资产' : '登记资产'" :visible.sync="formVisible" size="640px" append-to-body>
      <el-form ref="form" class="asset-form" :model="form" :rules="rules" label-position="top">
        <el-row :gutter="14"><el-col :span="12"><el-form-item label="资产编号" prop="assetNo"><el-input v-model.trim="form.assetNo" /></el-form-item></el-col><el-col :span="12"><el-form-item label="资产名称" prop="assetName"><el-input v-model.trim="form.assetName" /></el-form-item></el-col></el-row>
        <el-row :gutter="14"><el-col :span="8"><el-form-item label="版本"><el-input v-model.trim="form.assetVersion" /></el-form-item></el-col><el-col :span="8"><el-form-item label="类型" prop="assetType"><el-select v-model="form.assetType"><el-option label="硬件" value="hardware" /><el-option label="算法" value="algorithm" /><el-option label="平台" value="platform" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="阶段" prop="assetStage"><el-select v-model="form.assetStage"><el-option v-for="item in stages" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item></el-col></el-row>
        <el-row :gutter="14"><el-col :span="12"><el-form-item label="主负责人" prop="primaryOwnerId"><el-select v-model="form.primaryOwnerId" filterable><el-option v-for="item in writableMembers" :key="item.id" :label="memberLabel(item)" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="备份负责人"><el-select v-model="form.backupOwnerId" clearable filterable><el-option v-for="item in activeMembers" :key="item.id" :disabled="Number(item.id)===Number(form.primaryOwnerId)" :label="memberLabel(item)" :value="item.id" /></el-select></el-form-item></el-col></el-row>
        <el-row :gutter="14"><el-col :span="8"><el-form-item label="关键资产"><el-switch v-model="critical" active-text="是" inactive-text="否" /></el-form-item></el-col><el-col :span="8"><el-form-item label="状态"><el-select v-model="form.status"><el-option label="活跃" value="ACTIVE" /><el-option label="停用" value="INACTIVE" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="复用次数"><el-input-number v-model="form.reuseCount" :min="0" :max="99999" /></el-form-item></el-col></el-row>
        <el-form-item label="能力说明"><el-input v-model.trim="form.capacityDesc" type="textarea" :rows="3" maxlength="1000" show-word-limit /></el-form-item>
        <el-form-item label="代码仓库"><el-input v-model.trim="form.repositoryUrl" placeholder="https://…" /></el-form-item><el-form-item label="资产文档"><el-input v-model.trim="form.documentUrl" placeholder="https://…" /></el-form-item><el-form-item label="测试集"><el-input v-model.trim="form.testSetUrl" placeholder="https://…" /></el-form-item><el-form-item label="部署包"><el-input v-model.trim="form.deployPackageUrl" placeholder="https://…" /></el-form-item>
        <div class="drawer-actions"><el-button @click="formVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存资产</el-button></div>
      </el-form>
    </el-drawer>
  </main>
</template>

<script>
import { addAsset, deactivateAsset, listAssetRisks, listAssets, updateAsset } from '@/api/lab/asset'
import { listMembers } from '@/api/lab/member'

export default {
  name: 'LabAsset',
  data() { return { query: { pageNum: 1, pageSize: 20, assetName: '', assetType: '', assetStage: '', singlePointRisk: this.routeBoolean(this.$route.query.singlePointRisk) }, rows: [], riskRows: [], total: 0, members: [], requestToken: 0, loading: false, saving: false, formVisible: false, form: {}, stages: [{ label: '验证中', value: 'VERIFYING' }, { label: '已部署', value: 'DEPLOYED' }, { label: '已验收', value: 'ACCEPTED' }], rules: { assetNo: [{ required: true, message: '请输入资产编号', trigger: 'blur' }], assetName: [{ required: true, message: '请输入资产名称', trigger: 'blur' }], assetType: [{ required: true, message: '请选择资产类型', trigger: 'change' }], assetStage: [{ required: true, message: '请选择资产阶段', trigger: 'change' }], primaryOwnerId: [{ required: true, message: '请选择主负责人', trigger: 'change' }] }} },
  computed: { activeMembers() { return this.members.filter(item => item.memberStatus === 'ACTIVE') }, currentMember() { return this.members.find(item => Number(item.userId) === Number(this.$store.state.user.id)) || null }, writableMembers() { return this.activeMembers.filter(item => this.canWriteOwner(item.id)) }, riskCount() { return this.riskRows.length }, inUseCount() { return this.rows.filter(item => ['DEPLOYED', 'ACCEPTED'].includes(item.assetStage)).length }, reuseTotal() { return this.rows.reduce((sum, item) => sum + Number(item.reuseCount || 0), 0) }, critical: { get() { return this.form.criticalFlag === '1' }, set(value) { this.$set(this.form, 'criticalFlag', value ? '1' : '0') } }},
  created() { this.loadMembers(); this.load() },
  methods: {
    loadMembers() { listMembers({ pageNum: 1, pageSize: 500, memberStatus: 'ACTIVE' }).then(res => { this.members = res.rows || [] }) },
    load() { const token = ++this.requestToken; this.loading = true; return Promise.all([listAssets(this.query), listAssetRisks({})]).then(([page, risks]) => { if (token !== this.requestToken) return; this.rows = page.rows || []; this.total = Number(page.total || 0); this.riskRows = risks.data || [] }).finally(() => { if (token === this.requestToken) this.loading = false }) }, search() { this.query.pageNum = 1; this.load() }, reset() { this.query = { pageNum: 1, pageSize: 20, assetName: '', assetType: '', assetStage: '', singlePointRisk: false }; this.load() },
    emptyForm() { return { assetNo: '', assetName: '', assetVersion: '', assetType: 'algorithm', assetStage: 'VERIFYING', primaryOwnerId: null, backupOwnerId: null, testSetUrl: '', deployPackageUrl: '', documentUrl: '', resourceUrl: '', repositoryUrl: '', capacityDesc: '', reuseCount: 0, criticalFlag: '0', status: 'ACTIVE' } }, openCreate() { this.form = this.emptyForm(); this.formVisible = true }, openEdit(row) { this.form = { ...row }; this.formVisible = true },
    save() { this.$refs.form.validate(valid => { if (!valid) return; if (this.form.backupOwnerId && Number(this.form.backupOwnerId) === Number(this.form.primaryOwnerId)) return this.$message.warning('主负责人和备份负责人必须不同'); this.saving = true; (this.form.id ? updateAsset(this.form) : addAsset(this.form)).then(() => { this.$message.success('资产已保存'); this.formVisible = false; this.load() }).finally(() => { this.saving = false }) }) },
    deactivate(row) { this.$confirm(`停用资产「${row.assetName}」？历史记录会保留。`, '停用资产').then(() => deactivateAsset(row.id, row.version)).then(() => { this.$message.success('资产已停用'); this.load() }).catch(() => {}) },
    canWriteOwner(ownerId) { const roles = (this.$store.getters.roles || []).map(item => String(item).toLowerCase()); if (roles.includes('admin') || roles.includes('lab_manager') || roles.includes('manager')) return true; if (!this.currentMember) return false; if (Number(this.currentMember.id) === Number(ownerId)) return true; const owner = this.members.find(item => Number(item.id) === Number(ownerId)); return roles.includes('lab_lead') && owner && owner.bizLine === this.currentMember.bizLine }, routeBoolean(value) { return value === true || value === 'true' || value === '1' }, safeUrl(url) { return /^https?:\/\//i.test(String(url || '')) }, openUrl(url) { if (this.safeUrl(url)) window.open(url, '_blank', 'noopener,noreferrer') }, typeMark(type) { return ({ hardware: 'HW', algorithm: 'ALG', platform: 'PLT' })[type] || 'AST' }, stageLabel(stage) { const match = this.stages.find(item => item.value === stage); return match ? match.label : stage || '—' }, memberLabel(item) { return `${item.nickName || item.userName || item.memberNo} · ${item.bizLine || '未分线'}` }
  }
}
</script>

<style scoped lang="scss">
.asset-page { min-height:100%; padding:28px; color:#183442; background:#f3f5f2; }.asset-hero { display:flex; align-items:flex-end; justify-content:space-between; padding:27px 30px; border:1px solid #d9e1dc; border-radius:15px; background:linear-gradient(120deg,#fff 45%,#e3f1ed); }.asset-hero span { color:#2d716a; font-size:11px; letter-spacing:.16em; text-transform:uppercase; }.asset-hero h1 { margin:7px 0; font:600 30px Georgia,'Noto Serif SC',serif; }.asset-hero p { margin:0; color:#63757b; }
.asset-insight { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin:16px 0; }.asset-insight article { padding:17px 19px; border-left:3px solid #2e857d; border-radius:8px; background:#fff; box-shadow:0 5px 16px rgba(27,53,58,.05); }.asset-insight article.risk { border-color:#ae4a3f; }.asset-insight span,.asset-insight small,.asset-insight strong { display:block; }.asset-insight span { color:#596d75; font-size:12px; }.asset-insight strong { margin:5px 0 2px; font:600 25px Georgia,serif; }.asset-insight small { color:#849197; }
.asset-ledger { padding:20px; border:1px solid #dce4df; border-radius:12px; background:#fff; }.filters { display:flex; align-items:center; gap:10px; margin-bottom:17px; }.filters .el-input,.filters .el-select { width:180px; }.risk-note { margin:-3px 0 15px; padding:10px 13px; color:#8b3d35; border-radius:7px; background:#fbefec; }.asset-name { display:flex; align-items:center; gap:11px; }.asset-name>span { display:grid; place-items:center; width:38px; height:38px; border-radius:9px; color:#216a64; background:#e7f2ef; font-size:10px; font-weight:700; }.asset-name>span.is-risk { color:#9b3f36; background:#f7e9e6; }.asset-name strong,.asset-name small,.sub { display:block; }.asset-name small,.sub { color:#849196; margin-top:3px; font-size:11px; }.stage-pill { color:#2b655f; padding:4px 8px; border-radius:10px; background:#edf5f3; }.risk-badge { color:#a23f35; font-weight:600; }.covered { color:#38766f; }.muted { color:#9aa4a8; }.danger { color:#a6413b; }
.asset-form { padding:8px 26px 28px; }.asset-form .el-select,.asset-form .el-date-editor { width:100%; }.drawer-actions { display:flex; justify-content:flex-end; gap:10px; padding-top:10px; }
@media(max-width:900px){.asset-page{padding:16px}.asset-insight{grid-template-columns:1fr 1fr}.filters{flex-wrap:wrap}}
</style>
