<template>
  <main class="ipr-page">
    <header class="ipr-hero"><div><span>知识产权进展</span><h1>知识产权进展台账</h1><p>让计划日、材料证据、受理与授权信息沿阶段完整留痕。</p></div><el-button v-hasPermi="['lab:ipr:add']" type="primary" icon="el-icon-plus" @click="openCreate">登记知识产权</el-button></header>
    <section class="stage-strip"><article v-for="stage in stages" :key="stage.value" :class="{ active: query.iprStage === stage.value }" role="button" tabindex="0" @click="toggleStage(stage.value)" @keydown.enter="toggleStage(stage.value)" @keydown.space.prevent="toggleStage(stage.value)"><span>{{ stage.index }}</span><div><strong>{{ stage.label }}</strong><small>本页 {{ stageCount(stage.value) }} 项</small></div></article></section>
    <section class="ipr-ledger">
      <div class="filters"><el-input v-model.trim="query.iprName" clearable prefix-icon="el-icon-search" placeholder="名称或编号" @keyup.enter.native="search" /><el-select v-model="query.iprType" clearable placeholder="类型" @change="search"><el-option v-for="item in types" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-select v-model="query.ownerId" clearable filterable placeholder="负责人" @change="search"><el-option v-for="item in members" :key="item.id" :label="memberLabel(item)" :value="item.id" /></el-select><el-select v-model="query.status" clearable placeholder="状态" @change="search"><el-option label="活跃" value="ACTIVE" /><el-option label="停用" value="INACTIVE" /></el-select><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></div>
      <el-table v-loading="loading" :data="rows" row-key="id">
        <el-table-column label="知识产权" min-width="260"><template slot-scope="scope"><div class="ipr-title"><span>{{ typeMark(scope.row.iprType) }}</span><div><strong>{{ scope.row.iprName }}</strong><small>{{ scope.row.iprNo }} · {{ typeLabel(scope.row.iprType) }}</small></div></div></template></el-table-column><el-table-column label="阶段" width="120"><template slot-scope="scope"><span class="stage-badge">{{ stageLabel(scope.row.iprStage) }}</span></template></el-table-column><el-table-column label="负责人" min-width="130"><template slot-scope="scope"><strong>{{ scope.row.ownerName || `#${scope.row.ownerId}` }}</strong><small class="sub">{{ scope.row.ownerBizLine || '—' }}</small></template></el-table-column>
        <el-table-column label="计划提交" width="125"><template slot-scope="scope"><span :class="{ overdue: isOverdue(scope.row) }">{{ scope.row.plannedSubmitDate || '—' }}<i v-if="isOverdue(scope.row)" class="el-icon-warning" /></span></template></el-table-column><el-table-column prop="actualSubmitDate" label="实际提交" width="115" /><el-table-column label="证据" width="100"><template slot-scope="scope"><el-button v-if="safeUrl(scope.row.evidenceUrl)" type="text" @click="openUrl(scope.row.evidenceUrl)">查看材料</el-button><span v-else>—</span></template></el-table-column>
        <el-table-column label="进展凭证" min-width="160"><template slot-scope="scope"><small v-if="scope.row.acceptanceNo" class="credential">受理 {{ scope.row.acceptanceNo }}</small><small v-if="scope.row.certificateNo" class="credential">证书 {{ scope.row.certificateNo }}</small><span v-if="!scope.row.acceptanceNo && !scope.row.certificateNo">—</span></template></el-table-column><el-table-column label="操作" width="145" fixed="right"><template slot-scope="scope"><template v-if="canWriteOwner(scope.row.ownerId)"><el-button v-hasPermi="['lab:ipr:edit']" type="text" @click="openEdit(scope.row)">更新进展</el-button><el-button v-hasPermi="['lab:ipr:remove']" type="text" class="danger" :disabled="scope.row.status !== 'ACTIVE'" @click="deactivate(scope.row)">停用</el-button></template><span v-else class="muted">只读</span></template></el-table-column>
        <template slot="empty"><el-empty description="暂无匹配知识产权记录" /></template>
      </el-table><pagination v-show="total>0" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @pagination="load" />
    </section>

    <el-drawer :title="form.id ? '更新知识产权进展' : '登记知识产权'" :visible.sync="formVisible" size="640px" append-to-body>
      <el-form ref="form" class="ipr-form" :model="form" :rules="rules" label-position="top">
        <el-row :gutter="14"><el-col :span="12"><el-form-item label="编号" prop="iprNo"><el-input v-model.trim="form.iprNo" /></el-form-item></el-col><el-col :span="12"><el-form-item label="名称" prop="iprName"><el-input v-model.trim="form.iprName" /></el-form-item></el-col></el-row>
        <el-row :gutter="14"><el-col :span="8"><el-form-item label="类型" prop="iprType"><el-select v-model="form.iprType"><el-option v-for="item in types" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="阶段" prop="iprStage"><el-select v-model="form.iprStage"><el-option v-for="item in stages" :key="item.value" :disabled="Boolean(form.id) && !manager && stageIndex(item.value) < stageIndex(originalStage)" :label="item.label" :value="item.value" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="负责人" prop="ownerId"><el-select v-model="form.ownerId" filterable><el-option v-for="item in writableMembers" :key="item.id" :label="memberLabel(item)" :value="item.id" /></el-select></el-form-item></el-col></el-row>
        <el-row :gutter="14"><el-col :span="12"><el-form-item label="计划提交日" prop="plannedSubmitDate"><el-date-picker v-model="form.plannedSubmitDate" type="date" value-format="yyyy-MM-dd" /></el-form-item></el-col><el-col :span="12"><el-form-item label="实际提交日" :required="stageAtLeast('SUBMITTED')"><el-date-picker v-model="form.actualSubmitDate" type="date" value-format="yyyy-MM-dd" :picker-options="actualPicker" /></el-form-item></el-col></el-row>
        <el-form-item v-if="stageAtLeast('ACCEPTED')" label="受理编号" prop="acceptanceNo"><el-input v-model.trim="form.acceptanceNo" /></el-form-item><el-row v-if="stageAtLeast('AUTHORIZED')" :gutter="14"><el-col :span="12"><el-form-item label="证书编号" prop="certificateNo"><el-input v-model.trim="form.certificateNo" /></el-form-item></el-col><el-col :span="12"><el-form-item label="授权日期"><el-date-picker v-model="form.authorizedDate" type="date" value-format="yyyy-MM-dd" /></el-form-item></el-col></el-row>
        <el-form-item label="证据 / 文档链接"><el-input v-model.trim="form.evidenceUrl" placeholder="https://…" /></el-form-item><el-form-item v-if="manager && isRollback" label="阶段回退原因" required><el-input v-model.trim="rollbackReason" type="textarea" :rows="3" placeholder="阶段回退会记录审计原因" /></el-form-item><el-form-item label="备注"><el-input v-model.trim="form.remark" type="textarea" :rows="2" /></el-form-item>
        <div class="drawer-actions"><el-button @click="formVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存进展</el-button></div>
      </el-form>
    </el-drawer>
  </main>
</template>

<script>
import { addIpr, deactivateIpr, listIpr, updateIpr } from '@/api/lab/ipr'
import { listMembers } from '@/api/lab/member'

export default {
  name: 'LabIpr',
  data() { return { query: { pageNum: 1, pageSize: 20, iprName: '', iprType: '', iprStage: this.$route.query.iprStage || '', ownerId: this.numberOrNull(this.$route.query.ownerId), status: '' }, rows: [], total: 0, members: [], requestToken: 0, loading: false, saving: false, formVisible: false, form: {}, originalStage: '', rollbackReason: '', stages: [{ index: '01', label: '草稿', value: 'DRAFT' }, { index: '02', label: '准备中', value: 'PREPARING' }, { index: '03', label: '已提交', value: 'SUBMITTED' }, { index: '04', label: '已受理', value: 'ACCEPTED' }, { index: '05', label: '已授权', value: 'AUTHORIZED' }], types: [{ label: '软件著作权', value: 'SOFTWARE_COPYRIGHT' }, { label: '专利', value: 'PATENT' }, { label: '认证', value: 'CERTIFICATION' }], actualPicker: { disabledDate(date) { return date.getTime() > Date.now() } }, rules: { iprNo: [{ required: true, message: '请输入编号', trigger: 'blur' }], iprName: [{ required: true, message: '请输入名称', trigger: 'blur' }], iprType: [{ required: true, message: '请选择类型', trigger: 'change' }], iprStage: [{ required: true, message: '请选择阶段', trigger: 'change' }], ownerId: [{ required: true, message: '请选择负责人', trigger: 'change' }], plannedSubmitDate: [{ required: true, message: '请选择计划提交日', trigger: 'change' }] }} },
  computed: { activeMembers() { return this.members.filter(item => item.memberStatus === 'ACTIVE') }, currentMember() { return this.members.find(item => Number(item.userId) === Number(this.$store.state.user.id)) || null }, writableMembers() { return this.activeMembers.filter(item => this.canWriteOwner(item.id)) }, manager() { const roles = (this.$store.getters.roles || []).map(item => String(item).toLowerCase()); return roles.includes('admin') || roles.includes('lab_manager') || roles.includes('manager') }, isRollback() { return this.form.id && this.stageIndex(this.form.iprStage) < this.stageIndex(this.originalStage) } },
  created() { this.loadMembers(); this.load() },
  methods: {
    loadMembers() { listMembers({ pageNum: 1, pageSize: 500 }).then(res => { this.members = res.rows || [] }) }, load() { const token = ++this.requestToken; this.loading = true; listIpr(this.query).then(res => { if (token !== this.requestToken) return; this.rows = res.rows || []; this.total = Number(res.total || 0) }).finally(() => { if (token === this.requestToken) this.loading = false }) }, search() { this.query.pageNum = 1; this.load() }, reset() { this.query = { pageNum: 1, pageSize: 20, iprName: '', iprType: '', iprStage: '', ownerId: null, status: '' }; this.load() }, toggleStage(stage) { this.query.iprStage = this.query.iprStage === stage ? '' : stage; this.search() },
    emptyForm() { return { iprNo: '', iprName: '', iprType: 'PATENT', iprStage: 'DRAFT', ownerId: null, plannedSubmitDate: '', actualSubmitDate: '', acceptanceNo: '', certificateNo: '', authorizedDate: '', evidenceUrl: '', status: 'ACTIVE', remark: '' } }, openCreate() { this.form = this.emptyForm(); this.originalStage = ''; this.rollbackReason = ''; this.formVisible = true }, openEdit(row) { this.form = { ...row }; this.originalStage = row.iprStage; this.rollbackReason = ''; this.formVisible = true },
    save() { this.$refs.form.validate(valid => { if (!valid) return; if (this.isRollback && !this.manager) return this.$message.warning('只有实验室负责人可以回退阶段'); if (this.stageAtLeast('SUBMITTED') && !this.form.actualSubmitDate) return this.$message.warning('已提交及后续阶段必须填写实际提交日'); if (this.stageAtLeast('ACCEPTED') && !this.form.acceptanceNo) return this.$message.warning('已受理及后续阶段必须填写受理编号'); if (this.stageAtLeast('AUTHORIZED') && !this.form.certificateNo) return this.$message.warning('已授权阶段必须填写证书编号'); if (this.isRollback && !this.rollbackReason) return this.$message.warning('阶段回退必须填写原因'); this.saving = true; (this.form.id ? updateIpr(this.form, this.rollbackReason) : addIpr(this.form)).then(() => { this.$message.success('知识产权进展已保存'); this.formVisible = false; this.load() }).finally(() => { this.saving = false }) }) },
    deactivate(row) { this.$confirm(`停用「${row.iprName}」？历史记录会保留。`, '停用记录').then(() => deactivateIpr(row.id, row.version)).then(() => { this.$message.success('记录已停用'); this.load() }).catch(() => {}) }, canWriteOwner(ownerId) { const roles = (this.$store.getters.roles || []).map(item => String(item).toLowerCase()); if (this.manager) return true; if (!this.currentMember) return false; if (Number(this.currentMember.id) === Number(ownerId)) return true; const owner = this.members.find(item => Number(item.id) === Number(ownerId)); return roles.includes('lab_lead') && owner && owner.bizLine === this.currentMember.bizLine }, stageAtLeast(stage) { return this.stageIndex(this.form.iprStage) >= this.stageIndex(stage) }, stageIndex(stage) { return this.stages.findIndex(item => item.value === stage) }, stageLabel(stage) { const item = this.stages.find(value => value.value === stage); return item ? item.label : stage || '—' }, typeLabel(type) { const item = this.types.find(value => value.value === type); return item ? item.label : type || '—' }, typeMark(type) { return ({ SOFTWARE_COPYRIGHT: '软著', PATENT: '专利', CERTIFICATION: '认证' })[type] || 'IPR' }, stageCount(stage) { return this.rows.filter(item => item.iprStage === stage).length }, isOverdue(item) { return item.status === 'ACTIVE' && this.stageIndex(item.iprStage) < this.stageIndex('SUBMITTED') && item.plannedSubmitDate && item.plannedSubmitDate < this.today() }, today() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}` }, safeUrl(url) { return /^https?:\/\//i.test(String(url || '')) }, openUrl(url) { if (this.safeUrl(url)) window.open(url, '_blank', 'noopener,noreferrer') }, memberLabel(item) { return `${item.nickName || item.userName || item.memberNo} · ${item.bizLine || '未分线'}` }, numberOrNull(value) { const parsed = Number(value); return Number.isFinite(parsed) && parsed > 0 ? parsed : null }
  }
}
</script>

<style scoped lang="scss">
.ipr-page { min-height:100%; padding:28px; color:#213641; background:#f4f3ef; }.ipr-hero { display:flex; justify-content:space-between; align-items:flex-end; padding:27px 30px; color:#f8f7f2; border-radius:15px; background:linear-gradient(128deg,#283943,#315f5b); }.ipr-hero span { color:#b6d5cf; font-size:11px; letter-spacing:.17em; text-transform:uppercase; }.ipr-hero h1 { margin:7px 0; font:600 30px Georgia,'Noto Serif SC',serif; }.ipr-hero p { margin:0; color:#d6e0dc; }
.stage-strip { display:grid; grid-template-columns:repeat(5,1fr); gap:1px; margin:16px 0; overflow:hidden; border:1px solid #dde2dd; border-radius:12px; background:#dde2dd; }.stage-strip article { display:flex; gap:10px; align-items:center; padding:14px 16px; cursor:pointer; background:#fff; }.stage-strip article.active { color:#fff; background:#276f68; }.stage-strip article>span { color:#9b7d55; font:600 19px Georgia,serif; }.stage-strip article.active>span { color:#cce4df; }.stage-strip strong,.stage-strip small { display:block; }.stage-strip small { margin-top:2px; color:#889397; }.stage-strip article.active small { color:#d2e5e1; }
.ipr-ledger { padding:20px; border:1px solid #dfe3df; border-radius:12px; background:#fff; }.filters { display:flex; gap:10px; margin-bottom:17px; }.filters .el-input,.filters .el-select { width:180px; }.ipr-title { display:flex; align-items:center; gap:11px; }.ipr-title>span { display:grid; place-items:center; width:42px; height:42px; border-radius:50%; color:#6c5133; background:#f0e8db; font-size:10px; font-weight:700; }.ipr-title strong,.ipr-title small,.sub,.credential { display:block; }.ipr-title small,.sub { margin-top:3px; color:#849095; font-size:11px; }.stage-badge { padding:4px 9px; color:#28645e; border-radius:10px; background:#eaf3f0; }.overdue { color:#a13e35; font-weight:600; }.overdue i { margin-left:5px; }.credential { line-height:1.6; color:#53666f; }.danger { color:#a13e35; }
.ipr-form { padding:8px 26px 28px; }.ipr-form .el-select,.ipr-form .el-date-editor { width:100%; }.drawer-actions { display:flex; justify-content:flex-end; gap:10px; padding-top:10px; }
@media(max-width:900px){.ipr-page{padding:16px}.stage-strip{grid-template-columns:1fr 1fr}.filters{flex-wrap:wrap}}
</style>
