<template>
  <main class="template-designer">
    <section class="designer-header">
      <div><span>TEMPLATE / IMMUTABLE REVISION</span><h1>报告模板设计器</h1><p>对数据源、过滤、列与渲染进行强类型编排，发布后只创建新修订</p></div>
      <div class="designer-header__meta"><i class="el-icon-lock" /> <span>不执行任意 Java 访问</span><b>{{ metadata.queryFields.length }} 个安全字段</b></div>
    </section>

    <section class="designer-toolbar">
      <el-select v-model="activeTemplateId" filterable placeholder="选择模板修订" @change="requestTemplateChange">
        <el-option v-for="item in templates" :key="item.id" :label="templateLabel(item)" :value="item.id"><span>{{ item.templateName }} · r{{ item.revisionNo }}</span><b v-if="item.defaultFlag==='1'">默认</b></el-option>
      </el-select>
      <div v-if="template.id" class="designer-toolbar__identity"><strong>{{ template.templateCode }}</strong><span>{{ template.periodType }} · {{ template.status }} · version {{ template.version }}</span></div>
      <div class="designer-toolbar__actions">
        <el-button size="small" icon="el-icon-setting" @click="settingsVisible=true">模板属性</el-button>
        <el-button v-hasPermi="['lab:template:config']" size="small" icon="el-icon-document-copy" :disabled="!template.id" @click="openSaveAs">另存为</el-button>
        <el-button v-hasPermi="['lab:template:import']" size="small" icon="el-icon-upload2" @click="$refs.importFile.click()">导入</el-button>
        <el-button v-hasPermi="['lab:template:export']" size="small" icon="el-icon-download" :disabled="!template.id" @click="downloadTemplate">导出</el-button>
        <el-button v-hasPermi="['lab:template:config']" size="small" :disabled="!canPublishDefault" @click="publishDefault">设为默认</el-button>
        <el-button v-hasPermi="['lab:report:generate']" size="small" icon="el-icon-video-play" :disabled="!canTestGenerate" :title="canTestGenerate ? '前往报告中心测试当前修订' : '仅最新、启用的月报模板可测试生成'" @click="testGenerate">测试生成</el-button>
        <el-button v-hasPermi="['lab:template:config']" type="primary" size="small" icon="el-icon-check" :loading="saving" :disabled="!template.id || !dirty" @click="saveRevision">保存新修订</el-button>
      </div>
      <input ref="importFile" class="sr-only" type="file" accept="application/json,.json" @change="handleImport">
    </section>

    <div v-if="loadError" class="designer-alert" role="alert"><span>模板加载失败，未保存的本地配置不会被提交。</span><button type="button" @click="bootstrap">重试</button></div>
    <section v-loading="loading" class="designer-grid">
      <section-tree :sections="sections" :selected-code="selectedCode" @select="selectedCode=$event" @reorder="replaceSections" @add="addSection" />
      <section-properties
        :section="selectedSection"
        :metadata="metadata"
        :period-type="template.periodType"
        :query="queryConfig"
        :render="renderConfig"
        @change="updateSelected"
        @query-change="updateQuery"
        @render-change="updateRender"
        @source-change="changeSource"
        @type-change="changeType"
        @remove="removeSection"
        @insert-variable="insertVariable"
      />
      <markdown-preview :markdown="preview" :loading="previewLoading" :dirty="dirty" />
    </section>

    <el-dialog :visible.sync="settingsVisible" title="模板属性" width="720px" append-to-body>
      <el-form label-position="top" size="small"><el-row :gutter="12"><el-col :span="12"><el-form-item label="模板名称"><el-input v-model.trim="template.templateName" maxlength="200" @input="markDirty" /></el-form-item></el-col><el-col :span="6"><el-form-item label="周期类型"><el-select v-model="template.periodType" disabled><el-option v-for="item in metadata.reportTypes" :key="item" :label="item" :value="item" /></el-select></el-form-item></el-col><el-col :span="6"><el-form-item label="状态"><el-select v-model="template.status" @change="markDirty"><el-option v-for="item in metadata.templateStatuses" :key="item" :label="item" :value="item" /></el-select></el-form-item></el-col></el-row>
        <el-divider content-position="left">页眉与版式</el-divider><el-row :gutter="12"><el-col :span="12"><el-form-item label="报告标题"><el-input v-model.trim="header.title" maxlength="200" @input="markDirty" /></el-form-item></el-col><el-col :span="12"><el-form-item label="副标题"><el-input v-model.trim="header.subtitle" maxlength="200" @input="markDirty" /></el-form-item></el-col><el-col :span="8"><el-form-item label="主题"><el-input v-model.trim="style.theme" maxlength="64" @input="markDirty" /></el-form-item></el-col><el-col :span="8"><el-form-item label="字体"><el-input v-model.trim="style.font" maxlength="100" @input="markDirty" /></el-form-item></el-col><el-col :span="8"><el-form-item label="主色"><el-color-picker v-model="style.primaryColor" @change="markDirty" /></el-form-item></el-col></el-row>
      </el-form><span slot="footer"><el-button type="primary" @click="settingsVisible=false">完成</el-button></span>
    </el-dialog>
    <el-dialog :visible.sync="saveAsVisible" title="另存为新模板家族" width="480px" append-to-body><el-form label-position="top"><el-form-item label="新模板编码"><el-input v-model.trim="saveAsCode" maxlength="64" placeholder="仅限字母、数字、_ 与 -" /></el-form-item><el-form-item label="新模板名称"><el-input v-model.trim="saveAsName" maxlength="200" /></el-form-item></el-form><span slot="footer"><el-button @click="saveAsVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveAs">创建家族</el-button></span></el-dialog>
  </main>
</template>

<script>
import { saveAs as saveBlob } from 'file-saver'
import { exportTemplate, getTemplateConfig, getTemplateMetadata, getTemplatePreview, importTemplate, listTemplateTree, publishTemplateDefault, saveTemplateAs, saveTemplateRevision } from '@/api/lab/template'
import SectionTree from './components/SectionTree'; import SectionProperties from './components/SectionProperties'; import MarkdownPreview from './components/MarkdownPreview'
const emptyMetadata = () => ({ sectionTypes: [], providers: [], operators: [], queryFields: [], reportTypes: [], templateStatuses: [], compatibleProviders: {}, providerPeriods: {}, providerFields: {}, providerMetrics: {}, freemarkerVariables: [] })
export default {
  name: 'LabTemplateDesigner', components: { SectionTree, SectionProperties, MarkdownPreview },
  beforeRouteLeave(to, from, next) { if (!this.dirty) { next(); return } this.$confirm('当前模板有未保存修改。离开设计器将丢弃这些修改，是否继续？', '离开模板设计器').then(() => next()).catch(() => next(false)) },
  data() { return { templates: [], activeTemplateId: null, template: {}, sections: [], selectedCode: '', metadata: emptyMetadata(), header: {}, style: {}, preview: '', previewLoading: false, loading: false, saving: false, loadError: false, dirty: false, settingsVisible: false, saveAsVisible: false, saveAsCode: '', saveAsName: '', previewTimer: null, loadToken: 0, localKey: 0 } },
  computed: {
    selectedSection() { return this.sections.find(item => item.sectionCode === this.selectedCode) || null },
    queryConfig() { return this.parse(this.selectedSection && this.selectedSection.queryConfigJson) },
    renderConfig() { return this.parse(this.selectedSection && this.selectedSection.renderConfigJson) },
    canPublishDefault() { return this.template.id && !this.dirty && this.template.latestFlag === '1' && this.template.status === 'ENABLED' && this.template.defaultFlag !== '1' },
    canTestGenerate() { return Boolean(this.template.id && !this.dirty && this.template.latestFlag === '1' && this.template.status === 'ENABLED' && this.template.periodType === 'MONTH') }
  },
  created() { this.bootstrap() }, beforeDestroy() { clearTimeout(this.previewTimer); this.loadToken++ },
  methods: {
    bootstrap() { this.loadError = false; this.loading = true; return Promise.all([getTemplateMetadata(), listTemplateTree()]).then(([metadata, tree]) => { this.metadata = Object.assign(emptyMetadata(), metadata.data || {}); this.templates = Array.isArray(tree.data) ? tree.data : []; const routeId = Number(this.$route.query.id); this.activeTemplateId = this.templates.some(item => Number(item.id) === routeId) ? routeId : (this.templates.find(item => item.latestFlag === '1' && item.defaultFlag === '1') || this.templates[0] || {}).id || null; if (this.activeTemplateId) return this.loadConfig(this.activeTemplateId) }).catch(() => { this.loadError = true }).finally(() => { this.loading = false }) },
    loadConfig(id) { const token = ++this.loadToken; this.loading = true; this.loadError = false; return Promise.all([getTemplateConfig(id), getTemplatePreview(id)]).then(([config, preview]) => { if (token !== this.loadToken) return; this.template = Object.assign({}, config.data.template || {}); this.sections = (config.data.sections || []).map(item => Object.assign({}, item, { _key: item.id || ++this.localKey })).sort((a, b) => Number(a.sortNo) - Number(b.sortNo)); this.header = this.parse(this.template.headerJson); this.style = this.parse(this.template.styleJson); this.selectedCode = (this.sections[0] || {}).sectionCode || ''; this.preview = preview.data || ''; this.dirty = false }).catch(() => { if (token === this.loadToken) this.loadError = true }).finally(() => { if (token === this.loadToken) this.loading = false }) },
    requestTemplateChange(id) { const previous = this.template.id; if (!this.dirty || !previous || Number(previous) === Number(id)) return this.loadConfig(id); return this.$confirm('当前模板有未保存修改。切换修订将丢弃这些修改，是否继续？', '切换模板修订').then(() => this.loadConfig(id)).catch(() => { this.activeTemplateId = previous }) },
    parse(value) { if (!value) return {}; if (typeof value === 'object') return JSON.parse(JSON.stringify(value)); try { const result = JSON.parse(value); return result && typeof result === 'object' ? result : {} } catch (e) { return {} } },
    templateLabel(item) { const flags = [item.defaultFlag === '1' ? '默认' : '', item.latestFlag === '1' ? '最新' : '历史', item.status === 'DISABLED' ? '已停用' : ''].filter(Boolean).join(' / '); return `${item.templateName} · r${item.revisionNo} · ${flags}` },
    replaceSections(items) { this.sections = items; this.markDirty() },
    updateSelected(value) { const code = this.selectedCode; this.replaceSection(code, value); if (value.sectionCode !== code) this.selectedCode = value.sectionCode },
    replaceSection(code, value) { this.sections = this.sections.map(item => item.sectionCode === code ? Object.assign({}, value, { _key: item._key }) : item); this.markDirty() },
    updateQuery(value) { this.updateSelected(Object.assign({}, this.selectedSection, { queryConfigJson: JSON.stringify(value) })) },
    updateRender(value) { this.updateSelected(Object.assign({}, this.selectedSection, { renderConfigJson: JSON.stringify(value) })) },
    addSection() { let index = this.sections.length + 1; let code = `SECTION_${index}`; while (this.sections.some(item => item.sectionCode === code)) code = `SECTION_${++index}`; const type = (this.metadata.sectionTypes || [])[0] || 'TABLE'; const provider = ((this.metadata.compatibleProviders || {})[type] || [])[0] || null; const section = { _key: `new-${++this.localKey}`, sectionCode: code, sectionName: '新章节', sectionType: type, sortNo: (this.sections.length + 1) * 10, dataSource: provider, queryConfigJson: '{"filters":[]}', renderConfigJson: '{}', styleConfigJson: '{}', manualFlag: type === 'MANUAL' ? '1' : '0', visibleFlag: '1', sensitiveFlag: provider === 'PERF_SUMMARY' ? '1' : '0', sensitivePermission: provider === 'PERF_SUMMARY' ? 'lab:report:sensitive' : null, version: 0 }; this.sections = this.sections.concat(section); this.selectedCode = code; this.markDirty() },
    removeSection() { if (!this.selectedSection) return; const section = Object.assign({}, this.selectedSection); const templateId = this.template.id; this.$confirm(`删除章节「${section.sectionName}」？仅会影响尚未保存的新修订。`, '删除章节').then(() => { if (Number(this.template.id) !== Number(templateId)) return; const index = this.sections.findIndex(item => item.sectionCode === section.sectionCode); if (index < 0) return; this.sections = this.sections.filter(item => item.sectionCode !== section.sectionCode).map((item, i) => Object.assign({}, item, { sortNo: (i + 1) * 10 })); if (this.selectedCode === section.sectionCode) this.selectedCode = (this.sections[Math.min(index, this.sections.length - 1)] || {}).sectionCode || ''; this.markDirty() }).catch(() => {}) },
    changeType(type) { if (!this.selectedSection || type === this.selectedSection.sectionType) return; const section = Object.assign({}, this.selectedSection); const templateId = this.template.id; const compatible = ((this.metadata.compatibleProviders || {})[type] || []); const incompatible = section.dataSource && !compatible.includes(section.dataSource); const apply = () => { if (Number(this.template.id) !== Number(templateId) || !this.sections.some(item => item.sectionCode === section.sectionCode)) return; const value = Object.assign({}, section, { sectionType: type, manualFlag: type === 'MANUAL' ? '1' : '0' }); if (incompatible || type === 'MANUAL') { value.dataSource = null; value.queryConfigJson = '{"filters":[]}'; value.renderConfigJson = type === 'MANUAL' ? '{"required":false,"placeholder":"请填写管理摘要"}' : '{}' } this.replaceSection(section.sectionCode, value) }; if (incompatible) this.$confirm('新章节类型与当前数据源不兼容。确认后将清空数据源、过滤和列配置。', '切换章节类型').then(apply).catch(() => {}); else apply() },
    changeSource(source) { if (!this.selectedSection || source === this.selectedSection.dataSource) return; const section = Object.assign({}, this.selectedSection); const templateId = this.template.id; const query = this.parse(section.queryConfigJson); const render = this.parse(section.renderConfigJson); const apply = () => { if (Number(this.template.id) !== Number(templateId) || !this.sections.some(item => item.sectionCode === section.sectionCode)) return; const value = Object.assign({}, section, { dataSource: source || null, queryConfigJson: '{"filters":[]}', renderConfigJson: section.sectionType === 'MANUAL' ? section.renderConfigJson : '{}' }); if (source === 'PERF_SUMMARY') { value.sensitiveFlag = '1'; value.sensitivePermission = 'lab:report:sensitive' } this.replaceSection(section.sectionCode, value) }; const configured = this.hasBoundConfig(query) || this.hasBoundConfig(render); if (configured) this.$confirm('切换数据源会清空与旧投影绑定的过滤、列、模板、指标和图表配置。', '确认切换数据源').then(apply).catch(() => {}); else apply() },
    insertVariable(variable) { const current = String(this.renderConfig.template || ''); this.updateRender(Object.assign({}, this.renderConfig, { template: `${current}${current ? ' ' : ''}\${${variable}}` })) },
    hasBoundConfig(value) { return Object.keys(value || {}).some(key => { const item = value[key]; if (Array.isArray(item)) return item.length > 0; if (item && typeof item === 'object') return Object.keys(item).length > 0; return item !== undefined && item !== null && item !== '' && item !== false }) },
    markDirty() { this.dirty = true; clearTimeout(this.previewTimer); this.previewTimer = setTimeout(this.buildLocalPreview, 450) },
    buildLocalPreview() { const lines = [`# ${this.header.title || this.template.templateName || '未命名报告'}`, '', `> ${this.template.periodType || 'MONTH'} · 待保存配置预览`, '']; this.sections.filter(item => item.visibleFlag !== '0').forEach(item => { lines.push(`## ${item.sectionName || item.sectionCode}`, '', `_${item.sectionType} / ${item.dataSource || 'MANUAL'}_`, ''); if (item.sectionType === 'MANUAL') lines.push(this.parse(item.renderConfigJson).placeholder || '请填写摘要', '') }); this.preview = lines.join('\n') },
    command(templateOverride) { return { sourceTemplateId: this.template.id, template: Object.assign({}, this.template, templateOverride || {}, { headerJson: JSON.stringify(this.header || {}), styleJson: JSON.stringify(this.style || {}) }), sections: this.sections.map((item, index) => Object.assign({}, item, { id: null, templateId: null, sortNo: (index + 1) * 10, _key: undefined })), expectedVersion: this.template.version } },
    validateLocal() { if (!this.template.templateName || !this.sections.length) { this.$message.error('模板名称与至少一个章节为必填'); return false } const codes = this.sections.map(item => item.sectionCode); if (codes.some(code => !/^[A-Za-z0-9_-]{1,64}$/.test(code || '')) || new Set(codes).size !== codes.length) { this.$message.error('章节标识必须合法且唯一'); return false } for (const section of this.sections) { const render = this.parse(section.renderConfigJson); if (section.sectionType === 'CHART' && render.chart && render.chart !== 'bar') { this.$message.error(`章节 ${section.sectionCode} 仅支持柱状图`); return false } if (section.sectionType === 'GROUP_TEXT' && !render.groupBy) { this.$message.error(`章节 ${section.sectionCode} 必须选择分组字段`); return false } if (section.sectionType === 'MANUAL') continue; const specs = ((this.metadata.providerFields || {})[section.dataSource] || []); const byName = specs.reduce((map, spec) => { map[spec.name] = spec; return map }, {}); const filters = this.parse(section.queryConfigJson).filters || []; for (const filter of filters) { const spec = byName[filter.field]; if (!spec || !(spec.operators || []).includes(filter.operator) || !this.validFilterValue(spec.type, filter.operator, filter.value)) { this.$message.error(`章节 ${section.sectionCode} 的过滤字段、操作符或值类型不合法`); return false } } const projected = (render.columns || []).map(item => typeof item === 'string' ? item : item.field).concat(render.groupBy || []).filter(Boolean); if (projected.some(field => !byName[field])) { this.$message.error(`章节 ${section.sectionCode} 使用了数据源未提供的投影字段`); return false } } return true },
    validFilterValue(type, operator, value) { const values = ['IN', 'BETWEEN'].includes(operator) ? value : [value]; if (!Array.isArray(values) || !values.length || (operator === 'BETWEEN' && values.length !== 2)) return false; return values.every(item => { if (type === 'NUMBER') return typeof item === 'number' && Number.isFinite(item); if (type === 'BOOLEAN') return typeof item === 'boolean'; if (type === 'DATE') return typeof item === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(item); if (type === 'DATETIME') return typeof item === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,9})?)?(?:Z|[+-]\d{2}:\d{2})$/.test(item); return typeof item === 'string' && Boolean(item.trim()) }) },
    saveRevision() { if (!this.validateLocal()) return; this.saving = true; return saveTemplateRevision(this.command()).then(response => { this.$message.success('已创建不可变的新模板修订'); const id = response.data && response.data.id; return this.bootstrap().then(() => { if (id) { this.activeTemplateId = id; return this.loadConfig(id) } }) }).finally(() => { this.saving = false }) },
    openSaveAs() { this.saveAsCode = `${this.template.templateCode || 'template'}_copy`; this.saveAsName = `${this.template.templateName || '模板'} 副本`; this.saveAsVisible = true },
    saveAs() { if (!/^[A-Za-z0-9_-]{1,64}$/.test(this.saveAsCode) || !this.saveAsName) { this.$message.error('请输入合法且新的模板编码与名称'); return } this.saving = true; return saveTemplateAs(this.command({ templateCode: this.saveAsCode, templateName: this.saveAsName })).then(response => { this.$message.success('新模板家族已创建'); this.saveAsVisible = false; const id = response.data && response.data.id; return this.bootstrap().then(() => { if (id) { this.activeTemplateId = id; return this.loadConfig(id) } }) }).finally(() => { this.saving = false }) },
    publishDefault() { const template = { id: this.template.id, version: this.template.version, name: this.template.templateName }; return this.$confirm(`将「${template.name}」设为同周期唯一默认模板？`, '发布默认模板').then(() => publishTemplateDefault(template.id, template.version)).then(() => { this.$message.success('默认模板已切换'); return this.bootstrap() }).catch(() => {}) },
    downloadTemplate() { const snapshot = { id: this.template.id, code: this.template.templateCode, revision: this.template.revisionNo }; return exportTemplate(snapshot.id).then(blob => saveBlob(new Blob([blob], { type: 'application/json' }), `${snapshot.code}-r${snapshot.revision}.json`)) },
    handleImport(event) { const file = event.target.files && event.target.files[0]; event.target.value = ''; if (!file) return; if (!/\.json$/i.test(file.name) || file.size > 2 * 1024 * 1024) { this.$message.error('请选择 2 MiB 内的 JSON 模板'); return } this.$prompt('导入始终创建新家族，请输入新模板编码。', '导入模板', { inputPattern: /^[A-Za-z0-9_-]{1,64}$/, inputErrorMessage: '仅限字母、数字、_ 与 -' }).then(({ value }) => importTemplate(file, value)).then(response => { this.$message.success('模板已导入'); const id = response.data && response.data.id; return this.bootstrap().then(() => { if (id) { this.activeTemplateId = id; return this.loadConfig(id) } }) }).catch(() => {}) },
    testGenerate() { if (!this.canTestGenerate) return; const navigation = this.$router.push({ path: '/lab/report', query: { templateId: String(this.template.id) }}); if (navigation && navigation.catch) navigation.catch(() => {}) }
  }
}
</script>

<style lang="scss" scoped>
.template-designer{min-height:100%;background:#e9edf1}.designer-header{display:flex;align-items:flex-end;justify-content:space-between;padding:25px 30px;color:#fff;background:#101a32}.designer-header>div:first-child>span{color:#72cec5;font:9px 'Arial Narrow',Arial;letter-spacing:.2em}.designer-header h1{margin:7px 0 4px;font-size:27px}.designer-header p{margin:0;color:#adb8cd;font-size:11px}.designer-header__meta{display:grid;grid-template-columns:auto auto;gap:2px 7px;align-items:center;color:#b8c2d5;font-size:9px}.designer-header__meta i{grid-row:1/3;color:#72cec5;font-size:20px}.designer-header__meta b{color:#fff}.designer-toolbar{position:sticky;z-index:12;top:0;display:flex;align-items:center;gap:13px;min-height:58px;padding:9px 20px;border-bottom:1px solid var(--lab-line);background:#fff;box-shadow:0 4px 13px rgba(19,32,58,.08)}.designer-toolbar>.el-select{width:285px}.designer-toolbar__identity{min-width:150px}.designer-toolbar__identity strong,.designer-toolbar__identity span{display:block}.designer-toolbar__identity strong{color:var(--lab-indigo-deep);font-size:11px}.designer-toolbar__identity span{margin-top:3px;color:var(--lab-ink-soft);font-size:8px}.designer-toolbar__actions{display:flex;flex:1;justify-content:flex-end;gap:5px}.designer-toolbar__actions .el-button+.el-button{margin-left:0}.designer-grid{display:grid;grid-template-columns:260px minmax(440px,1.15fr) minmax(340px,.85fr);gap:1px;min-height:calc(100vh - 185px);background:#d7dce5}.designer-alert{display:flex;align-items:center;justify-content:space-between;padding:10px 20px;color:#873f3d;background:#fff0ef;font-size:10px}.designer-alert button{border:0;color:#9b3939;background:transparent;font-weight:700}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.el-dialog .el-select{width:100%}@media(max-width:1250px){.designer-toolbar{align-items:flex-start;flex-wrap:wrap}.designer-toolbar__actions{width:100%;justify-content:flex-start;overflow:auto}.designer-grid{grid-template-columns:230px minmax(430px,1fr)}.designer-grid>:last-child{grid-column:1/3;min-height:420px}}@media(max-width:760px){.designer-header{align-items:flex-start;gap:16px;flex-direction:column}.designer-toolbar>.el-select{width:100%}.designer-grid{display:block}.designer-grid>*{min-height:420px}}
::v-deep .el-dialog{max-width:calc(100vw - 24px)}
</style>
