<template>
  <section class="score-breakdown">
    <div v-if="!score" class="empty"><i class="el-icon-data-analysis" /><span>选择一条反馈查看计分事实链</span></div>
    <template v-else>
      <header><div><span>Evidence-based feedback</span><h3>{{ title }}</h3><p>修订 {{ score.revisionNo || '预览' }} · 截止 {{ score.cutoffTime || detail.cutoff || '当前' }}</p></div><div class="score-orb" :class="{ 'is-red': activeRedLine }"><strong>{{ number(total.total != null ? total.total : score.score) }}</strong><small>/ 100</small></div></header>
      <div class="component-grid"><article><span>交付</span><strong>{{ number(total.delivery != null ? total.delivery : score.deliveryScore) }}</strong><small>最高 60</small></article><article><span>质量</span><strong>{{ number(total.quality != null ? total.quality : score.qualityScore) }}</strong><small>最高 25</small></article><article><span>协同</span><strong>{{ number(total.collaboration != null ? total.collaboration : score.collaborationScore) }}</strong><small>最高 15</small></article></div>
      <div v-if="activeRedLine" class="redline"><i class="el-icon-warning" /><div><strong>当前存在红线事实</strong><p>{{ score.redLineReason || triggerSummary }}</p></div></div><div v-else-if="score.redLineFlag === '1' && score.revokedFlag === '1'" class="revoked"><i class="el-icon-circle-check" /> 红线已凭整改证据撤销，原触发事实仍保留在修订快照中。</div>

      <el-collapse accordion>
        <el-collapse-item name="tasks"><template slot="title"><strong>任务交付与质量门禁</strong><span>{{ tasks.length }} 项事实</span></template><div v-for="task in tasks" :key="task.taskId" class="fact-card"><div class="fact-card__title"><strong>{{ task.title || `任务 #${task.taskId}` }}</strong><span>{{ task.effectiveResult || '未确认' }} · 贡献 {{ number(task.deliveryContribution) }}</span></div><p>权重 {{ number(task.perfWeight) }} · 系数 {{ number(task.coefficient) }} · 质量通过率 {{ percent(task.qualityRate) }}</p><div class="chips"><span v-for="gate in task.qualityGates || []" :key="gate.gateId" :class="{ passed: gate.included }">{{ gate.gateName || gate.gateNo }} · {{ gate.included ? '计入' : exclusion(gate.exclusionReason) }}</span></div><div v-if="(task.evidence || []).length" class="evidence"><b>交付证据</b><button v-for="item in task.evidence" :key="item.evidenceId" type="button" :disabled="!safeUrl(item.url)" @click="openUrl(item.url)">{{ item.title || item.type || `证据 #${item.evidenceId}` }} · {{ item.included ? '已计入' : exclusion(item.exclusionReason) }}</button></div></div><el-empty v-if="!tasks.length" description="无重点月任务事实" :image-size="60" /></el-collapse-item>
        <el-collapse-item name="collaboration"><template slot="title"><strong>协同事实</strong><span>{{ collaborationItems.length }} 条</span></template><div v-for="item in collaborationItems" :key="item.recordId" class="fact-row"><div><strong>{{ categoryLabel(item.category) }}</strong><small>#{{ item.recordId }} · {{ item.reviewStatus }} · {{ item.included ? '计入' : exclusion(item.exclusionReason) }}</small></div><span :class="{ positive: number(item.appliedPoints) > 0 }">{{ number(item.appliedPoints) }}</span></div><el-empty v-if="!collaborationItems.length" description="无协同事实" :image-size="60" /></el-collapse-item>
        <el-collapse-item name="assets"><template slot="title"><strong>资产主备与红线</strong><span>{{ assetFacts.length }} 项</span></template><div v-for="item in assetFacts" :key="item.assetId" class="fact-row"><div><strong>{{ item.assetName || `资产 #${item.assetId}` }}</strong><small>活跃备份 {{ item.activeBackup ? '有' : '无' }} · 季度培养 {{ item.quarterBackupTraining ? '有' : '无' }}</small></div><span :class="{ danger: !item.activeBackup && !item.quarterBackupTraining }">{{ item.qualifyingCollaborationIds && item.qualifyingCollaborationIds.length ? `证据 #${item.qualifyingCollaborationIds.join(', #')}` : '—' }}</span></div><el-empty v-if="!assetFacts.length" description="无关键资产事实" :image-size="60" /></el-collapse-item>
      </el-collapse>
    </template>
  </section>
</template>

<script>
export default {
  name: 'ScoreBreakdown',
  props: { score: { type: Object, default: null }, memberName: { type: String, default: '' }},
  computed: {
    detail() { if (!this.score) return {}; if (this.score.detail && typeof this.score.detail === 'object') return this.score.detail; try { return JSON.parse(this.score.detailJson || '{}') || {} } catch (error) { return {} } },
    total() { return this.detail.totals || {} }, tasks() { return Array.isArray(this.detail.tasks) ? this.detail.tasks : [] }, collaborationItems() { return (((this.detail || {}).collaboration || {}).items) || [] }, assetFacts() { return Array.isArray(this.detail.assetFacts) ? this.detail.assetFacts : [] },
    triggers() { return Array.isArray(this.detail.redLineTriggers) ? this.detail.redLineTriggers : [] }, activeRedLine() { return this.score.redLineFlag === '1' && this.score.revokedFlag !== '1' }, triggerSummary() { return this.triggers.map(item => item.code).join('；') || '请查看红线事实详情' }, title() { return `${this.memberName || `成员 #${this.score.memberId || '—'}`} · ${this.score.period || this.detail.period || '绩效预览'}` }
  },
  methods: {
    number(value) { const parsed = Number(value || 0); return Number.isFinite(parsed) ? Number(parsed.toFixed(2)) : 0 }, percent(value) { return `${Math.round(Number(value || 0) * 100)}%` }, safeUrl(url) { return /^https?:\/\//i.test(String(url || '')) }, openUrl(url) { if (this.safeUrl(url)) window.open(url, '_blank', 'noopener,noreferrer') }, categoryLabel(value) { return ({ CROSS_DEPT: '跨部门支持', KNOWLEDGE: '知识分享', BACKUP: '备份培养', OVERDUE: '逾期扣分', DEDUCTION: '人工扣分' })[value] || value || '协同事实' }, exclusion(value) { return ({ REVIEW_NOT_APPROVED: '未审核', MISSING_EVIDENCE: '缺证据', CATEGORY_CAP_REACHED: '已达上限', GATE_NOT_PASSED: '门禁未通过', NO_BOUND_EVIDENCE: '未绑定证据', BOUND_EVIDENCE_NOT_APPROVED: '证据未审核', AUDIT_NOT_APPROVED: '证据未审核', MISSING_EVIDENCE_URL: '缺证据链接' })[value] || value || '未计入' }
  }
}
</script>

<style scoped lang="scss">
.score-breakdown { min-height:420px; }.score-breakdown>.empty { display:grid; place-items:center; align-content:center; gap:12px; height:420px; color:#829096; }.empty i { font-size:40px; color:#a8b9b6; }
.score-breakdown header { display:flex; align-items:center; justify-content:space-between; padding-bottom:18px; border-bottom:1px solid #e1e8e6; }.score-breakdown header span { color:#34716b; font-size:10px; letter-spacing:.15em; text-transform:uppercase; }.score-breakdown h3 { margin:5px 0; font:600 22px Georgia,'Noto Serif SC',serif; color:#193641; }.score-breakdown header p { margin:0; color:#77868d; font-size:12px; }.score-orb { display:grid; place-items:center; align-content:center; width:82px; height:82px; color:#fff; border-radius:50%; background:#16766e; }.score-orb.is-red { background:#a6483e; }.score-orb strong { font:600 25px Georgia,serif; }.score-orb small { font-size:10px; opacity:.8; }
.component-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:10px; margin:16px 0; }.component-grid article { padding:13px 14px; border-left:3px solid #39847d; border-radius:7px; background:#f2f7f5; }.component-grid span,.component-grid small,.component-grid strong { display:block; }.component-grid span { color:#64777e; font-size:11px; }.component-grid strong { margin:4px 0; font:600 20px Georgia,serif; }.component-grid small { color:#8a979b; }
.redline,.revoked { display:flex; gap:11px; align-items:flex-start; margin:15px 0; padding:13px 15px; border-radius:8px; }.redline { color:#903c34; background:#f9eae7; }.redline p { margin:3px 0 0; }.revoked { color:#2b6c65; background:#eaf4f1; }.score-breakdown ::v-deep .el-collapse-item__header { gap:10px; color:#223e49; }.score-breakdown ::v-deep .el-collapse-item__header span { margin-left:auto; margin-right:12px; color:#849096; font-size:11px; }
.fact-card { margin-bottom:10px; padding:13px 15px; border:1px solid #e2e8e6; border-radius:8px; }.fact-card__title { display:flex; justify-content:space-between; }.fact-card__title span { color:#39736d; }.fact-card p { color:#74848b; font-size:12px; }.chips { display:flex; flex-wrap:wrap; gap:6px; }.chips span { padding:4px 7px; color:#8b4640; border-radius:5px; background:#faefed; font-size:11px; }.chips span.passed { color:#2b6e67; background:#e9f3f0; }.evidence { display:flex; flex-wrap:wrap; gap:7px; margin-top:10px; }.evidence b { width:100%; font-size:11px; }.evidence button { color:#266b65; border:0; background:transparent; cursor:pointer; text-decoration:underline; }.evidence button:disabled { color:#8c979b; cursor:default; text-decoration:none; }
.fact-row { display:flex; justify-content:space-between; align-items:center; padding:10px 4px; border-bottom:1px solid #edf0ef; }.fact-row strong,.fact-row small { display:block; }.fact-row small { margin-top:3px; color:#7d8b91; }.fact-row>span { color:#6d7d84; }.fact-row>span.positive { color:#236e67; font-weight:700; }.fact-row>span.danger { color:#a13e35; }
</style>
