$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot; $sqlFile = Join-Path $root 'sql/ailab.sql'
if (-not (Test-Path -LiteralPath $sqlFile)) { throw "Missing SQL file: $sqlFile" }
$sql = Get-Content -LiteralPath $sqlFile -Raw -Encoding UTF8
function Require([bool]$ok, [string]$message) { if (-not $ok) { throw $message } }
function Split-TopLevel([string]$text) { $out = [System.Collections.Generic.List[string]]::new(); $quote = $false; $depth = 0; $start = 0; for ($i = 0; $i -lt $text.Length; $i++) { $c = $text[$i]; if ($c -eq "'" -and ($i -eq 0 -or $text[$i-1] -ne '\')) { $quote = -not $quote }; if (-not $quote -and $c -eq '(') { $depth++ } elseif (-not $quote -and $c -eq ')') { $depth-- } elseif (-not $quote -and $depth -eq 0 -and $c -eq ',') { $out.Add($text.Substring($start,$i-$start).Trim()); $start = $i + 1 } }; $out.Add($text.Substring($start).Trim()); return ,$out.ToArray() }
function Get-Tuples([string]$text) { $out = [System.Collections.Generic.List[object]]::new(); $quote = $false; $depth = 0; $start = -1; for ($i = 0; $i -lt $text.Length; $i++) { $c = $text[$i]; if ($c -eq "'" -and ($i -eq 0 -or $text[$i-1] -ne '\')) { $quote = -not $quote }; if (-not $quote -and $c -eq '(') { if ($depth -eq 0) { $start = $i + 1 }; $depth++ } elseif (-not $quote -and $c -eq ')') { $depth--; if ($depth -eq 0) { $out.Add((Split-TopLevel $text.Substring($start,$i-$start))) } } }; return ,$out.ToArray() }
function Get-InsertRows([string]$table) { $rows = [System.Collections.Generic.List[object]]::new(); $pattern = '(?is)INSERT\s+INTO\s+`' + [regex]::Escape($table) + '`\s*\((.*?)\)\s*VALUES\s*(.*?);'; $rx = [regex]::new($pattern); foreach ($m in $rx.Matches($sql)) { foreach ($row in (Get-Tuples $m.Groups[2].Value)) { $rows.Add($row) } }; return ,$rows.ToArray() }
function Unquote([string]$value) { return $value.Trim().Trim("'") }

$expectedTables = @('lab_goal','lab_task','lab_task_evidence','lab_task_quality_gate','lab_task_block_event','lab_reminder','lab_asset','lab_member','lab_skill','lab_member_skill','lab_one2one','lab_ipr','lab_collaboration_record','lab_perf_score','lab_period_close','lab_report_template','lab_report_section','lab_report_summary','lab_report_instance','lab_report_job')
$requiredFields = @{ lab_goal=@('parent_id','goal_level','year','period','goal_no','owner_id','weight','progress_rate','status','version'); lab_task=@('parent_id','goal_id','milestone_id','task_level','period','biz_line','task_type','owner_id','perf_weight','goal_weight','workflow_status','result_status','asset_id','coordination_required','coordination_owner_id','coordination_dept_id','coordination_content','coordination_support','current_block_flag','period_lock_flag','version'); lab_task_evidence=@('task_id','evidence_json','submitter_id','audit_status'); lab_task_quality_gate=@('task_id','gate_no','gate_status','evidence_id'); lab_task_block_event=@('task_id','episode_no','block_start_time','block_end_time','block_status'); lab_reminder=@('task_id','recipient_id','read_flag','idempotency_key'); lab_asset=@('primary_owner_id','backup_owner_id','resource_url'); lab_member=@('user_id','biz_line','leader_id'); lab_skill=@('skill_code','skill_category'); lab_member_skill=@('member_id','skill_id','proficiency_level'); lab_one2one=@('member_id','leader_id','meeting_date'); lab_ipr=@('ipr_type','ipr_stage','owner_id'); lab_collaboration_record=@('task_id','to_member_id','period','category','signed_score','evidence_url','reviewer_id','review_status'); lab_perf_score=@('member_id','period','revision_no','current_flag','detail_json','red_line_flag','revoked_flag','calibration_status'); lab_period_close=@('period','close_by','close_time','reopen_by','reopen_time','version'); lab_report_template=@('template_code','period_type','revision_no','latest_flag','default_flag','status','header_json','style_json','version'); lab_report_section=@('template_id','section_type','query_config_json','render_config_json','style_config_json','manual_flag','visible_flag','sensitive_flag','version'); lab_report_summary=@('period','biz_line','section_code','summary_json'); lab_report_instance=@('template_id','period','revision_no','lifecycle_status','current_flag','final_flag','sensitive_flag','source_data_json','source_perf_revision','content_json','content_markdown','json_status','json_path','json_error','markdown_status','markdown_path','markdown_error','word_status','word_path','word_error','pdf_status','pdf_path','pdf_error','version'); lab_report_job=@('report_id','job_type','job_status','progress_rate','attempt_count','error_message','idempotency_key','version') }
$tableMatches = [regex]::Matches($sql, '(?is)(CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?`?(lab_[a-z0-9_]+)`?\s*\(.*?\)\s*ENGINE=.*?;)')
$found = @($tableMatches | ForEach-Object { $_.Groups[2].Value.ToLowerInvariant() })
Require ($found.Count -eq 20 -and (Compare-Object ($expectedTables | Sort-Object) ($found | Sort-Object)).Count -eq 0) 'Missing or extra lab_* table detected.'
foreach ($m in $tableMatches) { $table=$m.Groups[2].Value; $statement=$m.Groups[1].Value; Require ($statement -match '(?is)ENGINE=InnoDB.*CHARSET=utf8mb4.*COLLATE=utf8mb4_general_ci.*COMMENT\s*=\s*''') "Engine/charset/collation/table comment missing: $table"; $body=$statement.Substring($statement.IndexOf('(')+1,$statement.LastIndexOf(') ENGINE')-$statement.IndexOf('(')-1); $columnMatches=[regex]::Matches($body,'(?is)(?:^|,)\s*`([a-z0-9_]+)`\s+(.*?)(?=,\s*`|,\s*(?:PRIMARY|UNIQUE|KEY)\b|$)'); $columns=@{}; foreach($c in $columnMatches){$columns[$c.Groups[1].Value]=$c.Groups[2].Value; Require ($c.Groups[2].Value -match '(?is)COMMENT\s+''') "Column comment missing: $table.$($c.Groups[1].Value)"}; foreach($audit in @('id','del_flag','create_by','create_time','update_by','update_time','remark')){Require $columns.ContainsKey($audit) "Audit column missing: $table.$audit"}; Require ($columns['id'] -match '(?is)bigint.*not\s+null.*auto_increment') "id type missing: $table"; foreach($field in $requiredFields[$table]){Require $columns.ContainsKey($field) "Required field missing: $table.$field"} }

$compactSql=($sql.ToLowerInvariant().Replace('`','') -replace '\s+',''); $uniqueContracts=@('uk_lab_goal_year_no(year,goal_no,active_unique_flag)','uk_lab_gate_task_no(task_id,gate_no,active_unique_flag)','uk_lab_reminder_idempotency(idempotency_key,active_unique_flag)','uk_lab_asset_no(asset_no,active_unique_flag)','uk_lab_member_user(user_id,active_unique_flag)','uk_lab_member_no(member_no,active_unique_flag)','uk_lab_skill_code(skill_code,active_unique_flag)','uk_lab_member_skill(member_id,skill_id,active_unique_flag)','uk_lab_ipr_no(ipr_no,active_unique_flag)','uk_lab_perf_member_period_rev(member_id,period,revision_no,active_unique_flag)','uk_lab_period_close_period(period,active_unique_flag)','uk_lab_report_tpl_code_rev(template_code,revision_no,active_unique_flag)','uk_lab_report_section(template_id,section_code,active_unique_flag)','uk_lab_report_summary(period,biz_line,section_code,active_unique_flag)','uk_lab_report_instance_no(report_no,active_unique_flag)','uk_lab_report_instance_period_rev(template_id,period,biz_line,revision_no,active_unique_flag)','uk_lab_report_job_no(job_no,active_unique_flag)','uk_lab_report_job_idempotency(idempotency_key,active_unique_flag)'); foreach($contract in $uniqueContracts){Require ($compactSql.Contains($contract)) "Required unique contract missing: $contract"}; Require (-not ($sql -match '(?is)UNIQUE\s+KEY[^\n]*del_flag')) 'UNIQUE KEY cannot include del_flag.'; foreach($table in @('lab_goal','lab_task_quality_gate','lab_reminder','lab_asset','lab_member','lab_skill','lab_member_skill','lab_ipr','lab_perf_score','lab_period_close','lab_report_template','lab_report_section','lab_report_summary','lab_report_instance','lab_report_job')){ $block=@($tableMatches | Where-Object { $_.Groups[2].Value -eq $table })[0].Groups[1].Value; Require ($block -match '(?is)active_unique_flag.*GENERATED\s+ALWAYS\s+AS') "Generated active uniqueness flag missing from CREATE TABLE: $table" }
$gateBlock=@($tableMatches | Where-Object { $_.Groups[2].Value -eq 'lab_task_quality_gate' })[0].Groups[1].Value; Require ($gateBlock -match '(?is)`evidence_id`\s+bigint.*COMMENT') 'Quality gate evidence_id contract missing.'; Require ($compactSql.Contains('keyidx_lab_gate_evidence(evidence_id)')) 'Quality gate evidence lookup index missing.'
$episodeBlock=@($tableMatches | Where-Object { $_.Groups[2].Value -eq 'lab_task_block_event' })[0].Groups[1].Value; Require ($episodeBlock -match '(?is)`episode_no`\s+int\s+NOT\s+NULL.*COMMENT') 'Block episode_no contract missing.'; Require ($compactSql.Contains('uniquekeyuk_lab_block_task_episode(task_id,episode_no)')) 'Block task/episode unique contract missing.'
Require (-not ($sql -match '(?is)ALTER\s+TABLE\s+`?lab_[a-z0-9_]+`?\s+ADD\s+COLUMN\s+`?active_unique_flag')) 'Active uniqueness must be declared in CREATE TABLE.'
$lookupContracts=@('keyidx_lab_goal_parent(parent_id)','keyidx_lab_goal_owner_status(owner_id,status)','keyidx_lab_goal_year_status(year,status)','keyidx_lab_task_parent(parent_id)','keyidx_lab_task_goal(goal_id)','keyidx_lab_task_milestone(milestone_id)','keyidx_lab_task_owner_period_workflow(owner_id,period,workflow_status)','keyidx_lab_task_dept(dept_id)','keyidx_lab_evidence_task(task_id)','keyidx_lab_gate_task_status(task_id,gate_status)','keyidx_lab_block_task_open(task_id,block_status,block_start_time)','keyidx_lab_reminder_recipient_read(recipient_id,read_flag)','keyidx_lab_asset_primary_status(primary_owner_id,status)','keyidx_lab_member_line_status(biz_line,member_status)','keyidx_lab_one2one_member_date(member_id,meeting_date)','keyidx_lab_ipr_owner_stage(owner_id,ipr_stage)','keyidx_lab_collab_member_period_status(to_member_id,period,review_status)','keyidx_lab_perf_member_period_current(member_id,period,current_flag)','keyidx_lab_report_section_tpl_sort(template_id,sort_no)','keyidx_lab_report_instance_tpl_period_lifecycle(template_id,period,lifecycle_status)','keyidx_lab_report_job_instance_status(report_id,job_status)'); foreach($contract in $lookupContracts){Require ($compactSql.Contains($contract)) "Required lookup index missing: $contract"}
$lookupContracts = @($lookupContracts | Where-Object { $_ -notmatch 'idx_lab_member_skill_member|idx_lab_report_summary_period' })
$dictPairs=[regex]::Matches($sql,"(?im)\(\s*\d+\s*,\s*\d+\s*,\s*'[^']*'\s*,\s*'([^']*)'\s*,\s*'(lab_[^']*)'") | ForEach-Object { ($_.Groups[2].Value+'|'+$_.Groups[1].Value).ToLowerInvariant() }; Require (($dictPairs | Select-Object -Unique).Count -eq $dictPairs.Count) 'Duplicate dictionary type/value tuple.'
$dicts=@('lab_biz_line|hardware','lab_biz_line|platform','lab_biz_line|algorithm','lab_biz_line|manage','lab_task_workflow_status|DRAFT','lab_task_workflow_status|ACTIVE','lab_task_workflow_status|PENDING_REVIEW','lab_task_workflow_status|CONFIRMED','lab_task_result_status|DOING','lab_task_result_status|EXCEEDED','lab_task_result_status|ONTIME','lab_task_result_status|DELAYED','lab_task_result_status|UNDONE','lab_task_type|key','lab_task_type|daily','lab_task_level|month','lab_task_level|week','lab_asset_type|hardware','lab_asset_type|algorithm','lab_asset_type|platform','lab_asset_stage|VERIFYING','lab_asset_stage|DEPLOYED','lab_asset_stage|ACCEPTED','lab_ipr_type|SOFTWARE_COPYRIGHT','lab_ipr_type|PATENT','lab_ipr_type|CERTIFICATION','lab_ipr_stage|DRAFTING','lab_ipr_stage|SUBMITTED','lab_ipr_stage|ACCEPTED','lab_ipr_stage|AUTHORIZED','lab_section_type|TABLE','lab_section_type|STAT','lab_section_type|TEXT','lab_section_type|MANUAL','lab_section_type|GROUP_TEXT','lab_section_type|CHART','lab_goal_status|ACTIVE','lab_goal_status|COMPLETED','lab_goal_status|TERMINATED'); foreach($pair in $dicts){Require ($dictPairs -contains $pair.ToLowerInvariant()) "Missing dictionary: $pair"}
$permissions=@('lab:dashboard:view','lab:goal:list','lab:goal:add','lab:goal:edit','lab:goal:remove','lab:task:list','lab:task:add','lab:task:edit','lab:task:remove','lab:task:evidence','lab:task:review','lab:member:list','lab:member:add','lab:member:edit','lab:member:remove','lab:skill:list','lab:skill:config','lab:one2one:list','lab:one2one:add','lab:asset:list','lab:asset:add','lab:asset:edit','lab:asset:remove','lab:ipr:list','lab:ipr:add','lab:ipr:edit','lab:perf:list','lab:perf:close','lab:perf:reopen','lab:perf:redline','lab:perf:revoke','lab:perf:calibrate','lab:template:list','lab:template:config','lab:template:import','lab:template:export','lab:report:list','lab:report:generate','lab:report:retry','lab:report:download','lab:report:finalize','lab:report:sensitive'); foreach($p in $permissions){Require ($sql.Contains("'$p'")) "Missing permission: $p"}
$jobs=@(); foreach($candidate in (Get-InsertRows 'sys_job')) { if ((($candidate -join ',') -match 'labScheduleTask\.')) { $jobs += ,$candidate } }; Require ($jobs.Count -eq 5) 'Exactly five real AI-lab sys_job seed rows required.'; $targets=@(); foreach($job in $jobs){Require ((Unquote $job[7]) -eq '0') 'AI-lab Quartz job must be enabled.'; $targets += Unquote $job[3]}; $expectedJobs=@('labScheduleTask.scanBlocks()','labScheduleTask.scanPendingTasks()','labScheduleTask.closeDuePeriods()','labScheduleTask.cleanReportTempFiles()','labScheduleTask.recoverReportJobs()'); Require ((Compare-Object ($targets | Sort-Object) ($expectedJobs | Sort-Object)).Count -eq 0) 'Quartz target rows are incomplete or duplicated.'
$template=@(); foreach($candidate in (Get-InsertRows 'lab_report_template')) { if ((Unquote $candidate[1]) -eq 'standard_month') { $template += ,$candidate } }; Require ($template.Count -eq 1) 'Exactly one standard_month template row required.'; Require ((Unquote $template[0][3]) -eq 'MONTH' -and (Unquote $template[0][5]) -eq '1' -and (Unquote $template[0][6]) -eq '1' -and (Unquote $template[0][7]) -eq 'ENABLED') 'Default monthly template flags/status invalid.'
$members=Get-InsertRows 'lab_member'; Require ($members.Count -eq 6) 'Exactly six demo member tuples required.'; $memberUsers=@(); foreach($member in $members) { $memberUsers += $member[1] }; Require (($memberUsers | Select-Object -Unique).Count -eq 6) 'Demo member sys_user ids must be distinct.'
$roleScopes=@{}; foreach($role in (Get-InsertRows 'sys_role')) { $roleScopes[(Unquote $role[2])] = Unquote $role[4] }; Require ($roleScopes['lab_manager'] -eq '1') 'Manager role must use all-data scope.'; Require ($roleScopes['lab_lead'] -eq '2') 'Lead role must use custom scope.'; Require ($roleScopes['lab_member'] -eq '5') 'Member role must use self scope.'
$roleDepts=Get-InsertRows 'sys_role_dept'; Require ($roleDepts.Count -eq 1 -and (Unquote $roleDepts[0][0]) -eq '30002' -and (Unquote $roleDepts[0][1]) -eq '101') 'Lead custom scope must map exactly to demo department 101.'; Require ($sql.Contains('DELETE FROM `sys_role_dept` WHERE `role_id` IN (30001,30002,30003);')) 'Exact lab role department cleanup is required.'
$expectedTaskLinks=@{'30001'='30001|30002';'30002'='30001|30002';'30003'='30001|30003';'30004'='30001|30003';'30005'='30001|30004'}; $seenTaskLinks=@{}; foreach($task in (Get-InsertRows 'lab_task')) { $taskId=Unquote $task[0]; if($expectedTaskLinks.ContainsKey($taskId)){ $seenTaskLinks[$taskId]=(Unquote $task[2])+'|'+(Unquote $task[3]) } }; Require ($seenTaskLinks.Count -eq $expectedTaskLinks.Count) 'Demo task relationship rows are incomplete.'; foreach($taskId in $expectedTaskLinks.Keys){Require ($seenTaskLinks[$taskId] -eq $expectedTaskLinks[$taskId]) "Demo task $taskId must reference annual goal and quarterly milestone."}
$menuMatch=[regex]::Match($sql,'(?is)INSERT\s+INTO\s+`sys_menu`\s*\((.*?)\)\s*VALUES\s*(.*?);'); Require $menuMatch.Success 'sys_menu seed missing.'; $menuColumns=(Split-TopLevel $menuMatch.Groups[1].Value).Count; foreach($row in (Get-Tuples $menuMatch.Groups[2].Value)){Require ($row.Count -eq $menuColumns) "sys_menu insert arity mismatch: expected $menuColumns, found $($row.Count)"}
$sectionTypes=@(); foreach($section in (Get-InsertRows 'lab_report_section')) { $sectionTypes += Unquote $section[4] }; Require (($sectionTypes | Sort-Object -Unique) -join ',' -eq 'CHART,GROUP_TEXT,MANUAL,STAT,TABLE,TEXT') 'All six report renderer type seed rows required.'
$seedIds=@{lab_report_job='30001';lab_report_instance='30001';lab_report_summary='30001,30002';lab_report_section='30001,30002,30003,30004,30005,30006';lab_report_template='30001';lab_period_close='30001';lab_perf_score='30001,30002,30003';lab_collaboration_record='30001';lab_ipr='30001,30002';lab_one2one='30001';lab_member_skill='30001,30002,30003,30004,30005';lab_skill='30001,30002,30003';lab_reminder='30001,30002';lab_task_block_event='30001,30002';lab_task_quality_gate='30001,30002';lab_task_evidence='30001,30002';lab_task='30001,30002,30003,30004,30005';lab_goal='30001,30002,30003,30004';lab_asset='30001,30002,30003';lab_member='30001,30002,30003,30004,30005,30006'}; Require (-not ($sql -match '(?is)DELETE\s+FROM[^;]+BETWEEN')) 'Range cleanup is unsafe.'; foreach($table in $seedIds.Keys){Require ($sql.Contains("DELETE FROM ``$table`` WHERE ``id`` IN ($($seedIds[$table]));")) "Exact cleanup IDs missing: $table"}
$users=Get-InsertRows 'sys_user'; Require ($users.Count -eq 6) 'Exactly six demo users required.'; $hashes=@(); $base='$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2'; foreach($user in $users){Require ((Unquote $user[10]) -eq '1') 'Demo users must be disabled.'; $hash=Unquote $user[9]; Require ($hash -match '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$') 'Demo password must be BCrypt shaped.'; Require ($hash -ne $base) 'Baseline admin hash is forbidden.'; $hashes += $hash}; Require (($hashes | Select-Object -Unique).Count -eq 6) 'Demo BCrypt hashes must be distinct.'
$insertCount=0; foreach($insert in [regex]::Matches($sql,'(?is)INSERT\s+INTO\s+`?[a-z0-9_]+`?\s*\(([^;]*?)\)\s*VALUES\s*([^;]*?);')) { $insertCount++; $arity=(Split-TopLevel $insert.Groups[1].Value).Count; foreach($row in (Get-Tuples $insert.Groups[2].Value)){Require ($row.Count -eq $arity) "INSERT arity mismatch: expected $arity, found $($row.Count)"} }; Require ($insertCount -gt 20) 'Expected substantive VALUES insert initialization.'
$quote=$false; $depth=0; for($i=0;$i -lt $sql.Length;$i++){ $c=$sql[$i]; if($c -eq "'" -and ($i -eq 0 -or $sql[$i-1] -ne '\')){$quote=-not $quote}; if(-not $quote -and $c -eq '('){$depth++}; if(-not $quote -and $c -eq ')'){$depth--; Require ($depth -ge 0) 'Unbalanced SQL closing parenthesis.'} }; Require (-not $quote -and $depth -eq 0) 'Unbalanced SQL string literal or parentheses.'
Write-Output "AI Lab SQL contract verified (tables=$($found.Count); dicts=$($dictPairs.Count); permissions=$($permissions.Count); jobs=$($jobs.Count); members=$($members.Count))"
