<template>
  <section class="filter-builder">
    <header><div><b>数据过滤</b><small>仅允许服务端白名单字段与操作符</small></div><el-button type="text" icon="el-icon-plus" :disabled="items.length>=10" @click="add">条件</el-button></header>
    <div v-for="(filter,index) in items" :key="index" class="filter-row">
      <el-select :value="filter.field" filterable placeholder="字段" @change="changeField(index,$event)"><el-option v-for="field in fields" :key="field" :label="`${field} · ${typeOf(field)}`" :value="field" /></el-select>
      <el-select :value="filter.operator" placeholder="操作符" @change="update(index,'operator',$event)"><el-option v-for="operator in operatorsFor(filter.field)" :key="operator" :label="operator" :value="operator" /></el-select>
      <el-input :value="display(filter.value)" :placeholder="valueHint(filter)" @input="updateValue(index,filter,$event)" />
      <el-button type="text" icon="el-icon-delete" aria-label="删除过滤条件" @click="remove(index)" />
    </div>
    <p v-if="!items.length">无额外过滤，数据源仍会按周期与用户权限强制裁剪。</p>
  </section>
</template>
<script>
export default { name: 'FilterBuilder', props: { value: { type: Array, default: () => [] }, fieldSpecs: { type: Array, default: () => [] }}, computed: { items() { return this.value || [] }, fields() { return this.fieldSpecs.map(item => item.name) } }, methods: { spec(field) { return this.fieldSpecs.find(item => item.name === field) || { type: 'STRING', operators: ['EQ', 'NE', 'IN'] } }, typeOf(field) { return this.spec(field).type }, operatorsFor(field) { return this.spec(field).operators || [] }, add() { const field = this.fields[0] || ''; this.$emit('input', this.items.concat({ field, operator: (this.operatorsFor(field)[0] || 'EQ'), value: '' })) }, remove(index) { this.$emit('input', this.items.filter((item, i) => i !== index)) }, update(index, key, value) { this.$emit('input', this.items.map((item, i) => i === index ? Object.assign({}, item, { [key]: value }) : item)) }, changeField(index, field) { this.$emit('input', this.items.map((item, i) => i === index ? { field, operator: this.operatorsFor(field)[0] || 'EQ', value: '' } : item)) }, updateValue(index, filter, value) { const convert = item => this.coerce(filter.field, item.trim()); const parsed = ['IN', 'BETWEEN'].includes(filter.operator) ? value.split(',').map(convert).filter(item => item !== '') : convert(value); this.update(index, 'value', parsed) }, coerce(field, value) { const type = this.typeOf(field); if (value === '') return ''; if (type === 'NUMBER') { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : value } if (type === 'BOOLEAN') { if (value === 'true' || value === '1') return true; if (value === 'false' || value === '0') return false } return value }, display(value) { return Array.isArray(value) ? value.join(', ') : value == null ? '' : String(value) }, valueHint(filter) { const type = this.typeOf(filter.field); if (filter.operator === 'BETWEEN') return `${type} 起始值, 结束值`; if (filter.operator === 'IN') return `${type} 值1, 值2`; if (type === 'BOOLEAN') return 'true 或 false'; if (type === 'DATETIME') return 'ISO-8601，如 2026-08-03T10:15:30Z'; return type === 'STRING' ? '固定值或 ${period}' : type } }}
</script>
<style lang="scss" scoped>
.filter-builder{padding:13px;border:1px solid var(--lab-line);background:#fafbfc}.filter-builder header{display:flex;align-items:center;justify-content:space-between}.filter-builder header b,.filter-builder header small{display:block}.filter-builder header b{color:var(--lab-indigo-deep);font-size:11px}.filter-builder header small{margin-top:3px;color:var(--lab-ink-soft);font-size:8px}.filter-row{display:grid;grid-template-columns:1.1fr .8fr 1.2fr 28px;gap:6px;margin-top:8px}.filter-row ::v-deep .el-input__inner{height:31px;padding:0 8px;font-size:9px}.filter-builder p{margin:11px 0 0;color:var(--lab-ink-soft);font-size:9px;line-height:1.6}
</style>
